---
title: "Promoter-mCherry-Terminator_fullplate_analysis"
author: "Jamie Auxillos"
date: "03/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(tibble)
library(stringr)
library(readr)
library(cowplot)
library(tidyqpcr)
library(here)



source(here("raw_data_analysis/code/shared_figure_formatting.R"))
```

```{r labels_pro_ter}
# define promoter and terminator levels in desired order
pro6  <- c("pPGK1", "pHSP26", "pRPS3", "pRPS13", "pSRO9", "pCLN2")
pro4  <- c("pPGK1", "pHSP26", "pRPS3", "pRPS13")
ter10 <- c("tPGK1", "tRPS3", "tRPS13",
           "tPAB1", "tHSP26", 
           "tCLN2", "tSRO9", 
           "tTOS6", "tSUN4", "tPMA1")
```


```{r}
pro_mCh_ter_n1 <- read.csv(here("raw_data_analysis/data/norm_platereader/promoter_terminator_swaps/mCherry_collection/pro-mCherry-ter_swaps_n=1.csv")) 
names(pro_mCh_ter_n1)[2] <- "sample_id"
names(pro_mCh_ter_n1)[3] <- "mCh_per_OD_at_max_gr"

pro_mCh_ter_n2 <- read.csv(here("raw_data_analysis/data/norm_platereader/promoter_terminator_swaps/mCherry_collection/pro-mCherry-ter_swaps_n=2.csv"))
names(pro_mCh_ter_n2)[2] <- "sample_id"
names(pro_mCh_ter_n2)[3] <- "mCh_per_OD_at_max_gr"

pro_mCh_ter_n3 <- read.csv(here("raw_data_analysis/data/norm_platereader/promoter_terminator_swaps/mCherry_collection/pro-mCherry-ter_swaps_n=3.csv")) 
names(pro_mCh_ter_n3)[2] <- "sample_id"
names(pro_mCh_ter_n3)[3] <- "mCh_per_OD_at_max_gr"

pro_mCh_ter_n4 <- read.csv(here("raw_data_analysis/data/norm_platereader/promoter_terminator_swaps/mCherry_collection/pro-mCherry-ter_swaps_n=4.csv")) 
names(pro_mCh_ter_n4)[2] <- "sample_id"
names(pro_mCh_ter_n4)[3] <- "mCh_per_OD_at_max_gr"

pro_mCh_ter_n5 <- read.csv(here("raw_data_analysis/data/norm_platereader/promoter_terminator_swaps/mCherry_collection/pro-mCherry-ter_swaps_n=5.csv"))
names(pro_mCh_ter_n5)[2] <- "sample_id"
names(pro_mCh_ter_n5)[3] <- "mCh_per_OD_at_max_gr"

pro_mCh_ter_n6 <- read.csv(here("raw_data_analysis/data/norm_platereader/promoter_terminator_swaps/mCherry_collection/pro-mCherry-ter_swaps_n=6.csv")) 
names(pro_mCh_ter_n6)[2] <- "sample_id"
names(pro_mCh_ter_n6)[3] <- "mCh_per_OD_at_max_gr"


pro_mCh_ter <-  bind_rows(pro_mCh_ter_n1, pro_mCh_ter_n2, pro_mCh_ter_n3, pro_mCh_ter_n4, pro_mCh_ter_n5, pro_mCh_ter_n6) %>%
        separate(sample_id, remove = FALSE,sep="_",into=c("Strain","BioRep")) %>%
  filter(!Strain %in% c('null', 'Null', 'POT1-ccdB')) %>%
  separate(Strain, remove = FALSE,sep="-",into=c("Promoter","mCherry","Terminator")) %>%
  mutate(Promoter = factor(Promoter, levels = pro6),
         Terminator = factor(Terminator, levels = ter10))

write_csv(pro_mCh_ter, here("raw_data_analysis/data/norm_platereader/promoter_terminator_swaps/mCherry_collection/pro-mCh-ter_swaps_raw.csv"))
```

```{r plot_norm, fig.width=9, fig.height=5}
plot_norm <- ggplot(data=pro_mCh_ter, aes(x=Terminator,y=mCh_per_OD_at_max_gr)) +
  geom_point(aes(color=Terminator),
               position=position_dodge(width = 0.5),size=1.8, alpha=1) +
  labs(y="mCh fluorescence/OD (AU)",x="Terminator") +
  facet_grid(~Promoter)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))

plot_norm + stat_summary(aes(Terminator,mCh_per_OD_at_max_gr),
    fun="mean",colour="black",
    geom="crossbar",size=0.2, width=0.5) 
```


```{r plot_se, fig.width=8, fig.height=2}
pro_mCh_ter_se <- pro_mCh_ter %>% 
  group_by(Strain,Promoter,Terminator) %>% 
  summarize(strain_mean = mean(mCh_per_OD_at_max_gr), # mean mCh fluorescence per strain
            strain_sd = sd(mCh_per_OD_at_max_gr), # mCh fluorescence sd per strain
            strain_n = n(),
            se = strain_sd/sqrt(strain_n), # mCh fluorescence se
            upper_limit = strain_mean+se, # Upper limit
            lower_limit = strain_mean-se # Lower limit
            )
pro_mCh_ter_se


plot_se <- ggplot(data=pro_mCh_ter_se, 
                  aes(x=Terminator,y=strain_mean)) +
  geom_point(aes(color=Terminator)) +
  labs(y="mCh fluorescence at maximum growth rate \n (normalised to OD)",x="Terminator") +
  facet_grid(~Promoter)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))+
  geom_errorbar(aes(ymax = strain_mean+se, ymin = strain_mean-se, color=Terminator))
plot_se
```

## Normalize relative to tPGK1

These next code chunks, until `tPGK1norm_combined`, can be combined into one using `group_by` - perhaps using `tidyqpcr::calculate_normvalue` on the way.

```{r pPGK1_tPGK1_norm, fig.width=3, fig.height=2}
pro_mCh_ter_pPGK1 <- pro_mCh_ter %>%
                  filter(Promoter %in% c('pPGK1'))

pro_mCh_ter_pPGK1_tPGK1 <- pro_mCh_ter_pPGK1 %>%
    filter(Terminator %in% c('tPGK1'))%>%
    summarize(mean_pPGK1_tPGK1 = mean(mCh_per_OD_at_max_gr))

norm_pro_mCh_ter_pPGK1 <- pro_mCh_ter_pPGK1 %>%
      mutate(norm_fluo_per_OD_at_max_gr = mCh_per_OD_at_max_gr / pro_mCh_ter_pPGK1_tPGK1$mean_pPGK1_tPGK1, remove=FALSE)

normPGK1plot <- ggplot(data=norm_pro_mCh_ter_pPGK1, aes(x=Terminator,y=norm_fluo_per_OD_at_max_gr)) +
  geom_point(aes(color=Terminator),
               position=position_dodge(width = 0.5),size=1.8, alpha=1) +
  labs(y="mCh fluorescence at maximum growth rate \n (normalised to OD relative to tPGK1)",x="Terminator") +
  facet_grid(~Promoter)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))

normPGK1plot + stat_summary(aes(Terminator,norm_fluo_per_OD_at_max_gr),
    fun="mean",colour="black",
    geom="crossbar",size=0.2, width=0.5) 
```


```{r pRPS3_tPGK1_norm, fig.width=3, fig.height=2}
pro_mCh_ter_pRPS3 <- pro_mCh_ter %>%
                  filter(Promoter %in% c('pRPS3'))

pro_mCh_ter_pRPS3_tPGK1 <- pro_mCh_ter_pRPS3 %>%
    filter(Terminator %in% c('tPGK1'))%>%
    summarize(mean_pRPS3_tPGK1 = mean(mCh_per_OD_at_max_gr))

norm_pro_mCh_ter_pRPS3 <- pro_mCh_ter_pRPS3 %>%
      mutate(norm_fluo_per_OD_at_max_gr = mCh_per_OD_at_max_gr / pro_mCh_ter_pRPS3_tPGK1$mean_pRPS3_tPGK1, remove=FALSE)

normRPS3plot <- ggplot(data=norm_pro_mCh_ter_pRPS3, aes(x=Terminator,y=norm_fluo_per_OD_at_max_gr)) +
  geom_point(aes(color=Terminator),
               position=position_dodge(width = 0.5),size=1.8, alpha=1) +
  labs(y="mCh fluorescence at maximum growth rate \n (normalised to OD relative to tPGK1)",x="Terminator") +
  facet_grid(~Promoter)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))

normRPS3plot + stat_summary(aes(Terminator,norm_fluo_per_OD_at_max_gr),
    fun="mean",colour="black",
    geom="crossbar",size=0.2, width=0.5) 
```

```{r pRPS13_tPGK1_norm, fig.width=3, fig.height=2}
pro_mCh_ter_pRPS13 <- pro_mCh_ter %>%
                  filter(Promoter %in% c('pRPS13'))

pro_mCh_ter_pRPS13_tPGK1 <- pro_mCh_ter_pRPS13 %>%
    filter(Terminator %in% c('tPGK1'))%>%
    summarize(mean_pRPS13_tPGK1 = mean(mCh_per_OD_at_max_gr))

norm_pro_mCh_ter_pRPS13 <- pro_mCh_ter_pRPS13 %>%
      mutate(norm_fluo_per_OD_at_max_gr = mCh_per_OD_at_max_gr / pro_mCh_ter_pRPS13_tPGK1$mean_pRPS13_tPGK1, remove=FALSE)

normRPS13plot <- ggplot(data=norm_pro_mCh_ter_pRPS13, aes(x=Terminator,y=norm_fluo_per_OD_at_max_gr)) +
  geom_point(aes(color=Terminator),
               position=position_dodge(width = 0.5),size=1.8, alpha=1) +
  labs(y="mCh fluorescence at maximum growth rate \n (normalised to OD relative to tPGK1)",x="Terminator") +
  facet_grid(~Promoter)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))

normRPS13plot + stat_summary(aes(Terminator,norm_fluo_per_OD_at_max_gr),
    fun="mean",colour="black",
    geom="crossbar",size=0.2, width=0.5) 
```

```{r pHSP26_tPGK1_norm, fig.width=3, fig.height=2}
pro_mCh_ter_pHSP26 <- pro_mCh_ter %>%
                  filter(Promoter %in% c('pHSP26'))

pro_mCh_ter_pHSP26_tPGK1 <- pro_mCh_ter_pHSP26 %>%
    filter(Terminator %in% c('tPGK1'))%>%
    summarize(mean_pHSP26_tPGK1 = mean(mCh_per_OD_at_max_gr))

norm_pro_mCh_ter_pHSP26 <- pro_mCh_ter_pHSP26 %>%
      mutate(norm_fluo_per_OD_at_max_gr = mCh_per_OD_at_max_gr / pro_mCh_ter_pHSP26_tPGK1$mean_pHSP26_tPGK1, remove=FALSE)

normHSP26plot <- ggplot(data=norm_pro_mCh_ter_pHSP26, aes(x=Terminator,y=norm_fluo_per_OD_at_max_gr)) +
  geom_point(aes(color=Terminator),
               position=position_dodge(width = 0.5),size=1.8, alpha=1) +
  labs(y="mCh fluorescence at maximum growth rate \n (normalised to OD relative to tPGK1)",x="Terminator") +
  facet_grid(~Promoter)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))

normHSP26plot + stat_summary(aes(Terminator,norm_fluo_per_OD_at_max_gr),
    fun="mean",colour="black",
    geom="crossbar",size=0.2, width=0.5) 
```

```{r pCLN2_tPGK1_norm, fig.width=3, fig.height=2}
pro_mCh_ter_pCLN2 <- pro_mCh_ter %>%
                  filter(Promoter %in% c('pCLN2'))

pro_mCh_ter_pCLN2_tPGK1 <- pro_mCh_ter_pCLN2 %>%
    filter(Terminator %in% c('tPGK1'))%>%
    summarize(mean_pCLN2_tPGK1 = mean(mCh_per_OD_at_max_gr))

norm_pro_mCh_ter_pCLN2 <- pro_mCh_ter_pCLN2 %>%
      mutate(norm_fluo_per_OD_at_max_gr = mCh_per_OD_at_max_gr / pro_mCh_ter_pCLN2_tPGK1$mean_pCLN2_tPGK1, remove=FALSE)

normCLN2plot <- ggplot(data=norm_pro_mCh_ter_pCLN2, aes(x=Terminator,y=norm_fluo_per_OD_at_max_gr)) +
  geom_point(aes(color=Terminator),
               position=position_dodge(width = 0.5),size=1.8, alpha=1) +
  labs(y="mCh fluorescence at maximum growth rate \n (normalised to OD relative to tPGK1)",x="Terminator") +
  facet_grid(~Promoter)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))

normCLN2plot + stat_summary(aes(Terminator,norm_fluo_per_OD_at_max_gr),
    fun="mean",colour="black",
    geom="crossbar",size=0.2, width=0.5) 
```

```{r pSRO9_tPGK1_norm, fig.width=3, fig.height=2}
pro_mCh_ter_pSRO9 <- pro_mCh_ter %>%
                  filter(Promoter %in% c('pSRO9'))

pro_mCh_ter_pSRO9_tPGK1 <- pro_mCh_ter_pSRO9 %>%
    filter(Terminator %in% c('tPGK1'))%>%
    summarize(mean_pSRO9_tPGK1 = mean(mCh_per_OD_at_max_gr))

norm_pro_mCh_ter_pSRO9 <- pro_mCh_ter_pSRO9 %>%
      mutate(norm_fluo_per_OD_at_max_gr = mCh_per_OD_at_max_gr / pro_mCh_ter_pSRO9_tPGK1$mean_pSRO9_tPGK1, remove=FALSE)

normSRO9plot <- ggplot(data=norm_pro_mCh_ter_pSRO9, aes(x=Terminator,y=norm_fluo_per_OD_at_max_gr)) +
  geom_point(aes(color=Terminator),
               position=position_dodge(width = 0.5),size=1.8, alpha=1) +
  labs(y="mCh fluorescence at maximum growth rate \n (normalised to OD relative to tPGK1)",x="Terminator") +
  facet_grid(~Promoter)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))

normSRO9plot + stat_summary(aes(Terminator,norm_fluo_per_OD_at_max_gr),
    fun="mean",colour="black",
    geom="crossbar",size=0.2, width=0.5) 
```

```{r tPGK1norm_combined}
norm_pro_mCh_ter_all <- bind_rows(norm_pro_mCh_ter_pPGK1, norm_pro_mCh_ter_pRPS3, norm_pro_mCh_ter_pRPS13,norm_pro_mCh_ter_pHSP26, norm_pro_mCh_ter_pCLN2, norm_pro_mCh_ter_pSRO9)

write_csv(norm_pro_mCh_ter_all, here("raw_data_analysis/data/norm_platereader/promoter_terminator_swaps/mCherry_collection/pro-mCh-ter_swaps_summary_PGK1_norm.csv"))
```


```{r tPGK1norm_combined_highexpression, fig.width=8, fig.height=2.5}
norm_allplot_high <- ggplot(data=norm_pro_mCh_ter_all %>% filter(!Promoter %in% c('pCLN2', 'pSRO9')),
                            aes(x=Terminator,y=norm_fluo_per_OD_at_max_gr)) +
  geom_point(aes(color=Terminator),
               position=position_dodge(width = 0.5),size=2.3, alpha=0.8) +
  scale_shape_manual(values=c(16,17, 15, 13)) +
  scale_colour_hue(h = c(0, 360)+20,l=60,c=60)+
  facet_grid(~Promoter)+
    labs(y="mCh fluorescence at maximum growth rate \n (relative to tPGK1)") +
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-3),
          axis.title.y=element_text(vjust=3),
        legend.position = "bottom")

norm_allplot_high_with_mean <- norm_allplot_high + stat_summary(aes(Terminator,norm_fluo_per_OD_at_max_gr),
    fun="mean",colour="black",
    geom="crossbar",size=0.2, width=0.5) +
    theme(legend.position = "none")
```


```{r tPGK1norm_combined_lowexpression, fig.width=8, fig.height=2.5}
norm_allplot_low <- ggplot(data=norm_pro_mCh_ter_all %>% filter(!Promoter %in% c('pHSP26', 'pPGK1', 'pRPS3', 'pRPS13')),
                            aes(x=Terminator,y=norm_fluo_per_OD_at_max_gr)) +
  geom_point(aes(color=Terminator),
               position=position_dodge(width = 0.5),size=2.3, alpha=0.8) +
    facet_grid(~Promoter)+
  scale_shape_manual(values=c(16,17, 15, 13)) +
  scale_colour_hue(h = c(0, 360)+20,l=60,c=60)+
  labs(y="",x="Terminator") +
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-3),
          axis.title.y=element_text(vjust=3),
        legend.position = "bottom")

norm_allplot_low_with_mean <- norm_allplot_low + stat_summary(aes(Terminator,norm_fluo_per_OD_at_max_gr),
    fun="mean",colour="black",
    geom="crossbar",size=0.2, width=0.5)

```


```{r plot_norm_se_1, fig.height=3, fig.width=6}
norm_pro_mCh_ter_se <- norm_pro_mCh_ter_all %>% 
  group_by(Strain,Promoter,Terminator) %>%
  summarize(strain_mean=mean(norm_fluo_per_OD_at_max_gr), 
            strain_sd=sd(norm_fluo_per_OD_at_max_gr), 
            strain_n=n(),
            se=strain_sd/sqrt(strain_n),
            upper_limit=strain_mean+se,
            lower_limit=strain_mean-se)  %>% 
  ungroup()
norm_pro_mCh_ter_se

plot_norm_se <- ggplot(data=norm_pro_mCh_ter_se, aes(x=Promoter,y=strain_mean)) +
  geom_point(aes(color=Promoter), size=2) +
  scale_colour_hue(h = c(0, 360)+20,l=60,c=60)+
  labs(y="mCh fluorescence/OD \n relative to tPGK1",x="Promoter") +
  facet_wrap(~Terminator, nrow=2)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))+
  geom_errorbar(aes(ymax = strain_mean+se, ymin = strain_mean-se, color=Promoter,  width=0.4))+
  geom_hline(yintercept=1, linetype="dotted", color = "grey50")
plot_norm_se
```

```{r plot_norm_se_2, fig.height=3, fig.width=6}
plot_norm_se_2 <- ggplot(data=norm_pro_mCh_ter_se, aes(x=Terminator,y=strain_mean)) +
  geom_point(aes(color=Terminator), size=2) +
  labs(y="mCh fluorescence/OD \n relative to tPGK1",x="Terminator") +
  facet_wrap(~Promoter, nrow=2)+
  scale_colour_hue(h = c(0, 360)+20,l=60,c=60)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))+
  geom_errorbar(aes(ymax = strain_mean+se, ymin = strain_mean-se, color=Terminator,  width=0.4))+
  geom_hline(yintercept=1, linetype="dotted", color = "grey50")
plot_norm_se_2
```

```{r plot_norm_se_pro4, fig.height=3, fig.width=7}
plot_norm_se_pro4 <- ggplot(data=filter(norm_pro_mCh_ter_se, Promoter %in% pro4),
                            aes(x=Terminator,y=strain_mean)) +
  geom_point(aes(color=Terminator), size=2) +
  labs(y="mCh fluorescence/OD \n relative to tPGK1",x="Terminator") +
  facet_wrap(~Promoter, nrow=1)+
  scale_colour_hue(h = c(0, 360)+20,l=60,c=60)+
  theme(axis.text.x=element_text(angle=90,vjust=0.5),
          axis.title.x=element_text(vjust=-2),
          axis.title.y=element_text(vjust=3))+
  geom_errorbar(aes(ymax = strain_mean+se, ymin = strain_mean-se, color=Terminator,  width=0.4))+
  geom_hline(yintercept=1, linetype="dotted", color = "grey50")
plot_norm_se_pro4
```

```{r plot_norm_all_points, fig.height=3, fig.width=6}

mCh_platereader_figure <- ggplot(data=norm_pro_mCh_ter_all %>% mutate(Terminator = str_remove(Terminator, "_long")) %>% rename(fluo_per_OD_at_max_gr = "norm_fluo_per_OD_at_max_gr")) +
  labs(x="Relative mCh fluorescence per OD relative to tPGK1", y="Terminator") +
  facet_wrap(~Promoter, nrow=2) +
  protein_raw_abundance_figure_options

```