---
title : "Probing 3'UTRs as modular regulators of gene expression"
output: 
  bookdown::pdf_book:
    includes:
      in_header: authors.tex
    template: "./formatting/template.tex"
    toc: false
    citation_package: natbib
bibliography: "./references/chimeraProject.bib"
biblio-style: "apalike"
link-citations: true
  
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(bookdown)
```
\begin{abstract}
Cis-regulatory elements (CREs) determining gene expression are abstracted into discrete modules, such as promoter, coding sequence, and terminator, and short sequence motifs within those.
Current cloning techniques mean that CREs are easy to construct and combine, i.e. they are practically modular.
However, it is unclear how much the effect of CREs on gene expression outcomes depends on other elements present in the same gene: are they functionally modular?
We probe the limitations of assuming independent effects in budding yeast, by confirming that the quantitative effect of a terminator depends on both promoter and coding sequence.
Next, we explore whether individual cis-regulatory motifs within terminator regions display similar context dependence.
We focus on suspected protein binding motifs in mRNA transcript 3'UTRs, inferred from transcriptome-wide datasets of mRNA decay.
Then we construct reporter genes with different combinations of inserted or removed motifs in 3 different terminator contexts, each expressed from 3 different promoters.
Our results show that the effects of individual CREs depend both on their host terminator, and also on the paired promoter at the opposite end of the coding sequence.
Observations that the same CRE can regulate gene expression differently in different host genes suggests that complex regulatory patterns are ubiquitous and need to be accounted for in designing synthetic genes.
Meanwhile, the consequences for novel CRE searches emphasise the need for improved search algorithms that include local and global context effects.
\end{abstract}