# A short script to check all required packages are installed
if(!require("bookdown")){
  install.packages("bookdown")
}
if(!require("tidyverse")){
  install.packages("tidyverse")
}
if(!require("Biostrings")){
  install.packages("Biostrings")
}
if(!require("latex2exp")){
  install.packages("latex2exp")
}
if(!require("glmnet")){
  install.packages("glmnet")
}
if(!require("stringi")){
  install.packages("stringi")
}
if(!require("broom")){
  install.packages("broom")
}
if(!require("readxl")){
  install.packages("readxl")
}
if(!require("cowplot")){
  install.packages("cowplot")
}
if(!require("tikzDevice")){
  install.packages("tikzDevice")
}
if(!require("BiocManager")){
  install.packages("BiocManager")
}
if(!require("BSgenome.Scerevisiae.UCSC.sacCer3")){
  BiocManager::install("BSgenome.Scerevisiae.UCSC.sacCer3")
}
if(!require("DECIPHER")){
  BiocManager::install("DECIPHER")
}
if(!require("devtools")){
  install.packages("devtools")
}
if(!require("tidyqpcr")){
  devtools::install_github("ewallace/tidyqpcr",build_vignettes = TRUE)
}
