---
title: "Motif position histograms"
output: html_document
---

```{r setup}
library(magick)
library(grid)
library(gridExtra)
library(broom)
library(gtable)
library(here)
library(dplyr)
library(readr)
library(stringr)

source(here("raw_data_analysis/code/shared_figure_formatting.R"))

### TSA1 and RPS3 insertion diagram

construct_to_label_dictionary_TSA1_RPS3 = tibble(construct = c("WT","modC","modE","modD","modA","modB","mod0"), 
                                       label = c("WT", "mod_NGG", "mod_HTH", "mod_HNH", "mod_NTN", "mod_NAA", "mod_NNN"),
                                       TSA1_UTR3 = str_c("tTSA1_",construct),
                                       RPS3_UTR3 = str_c("tRPS3_",construct))

TSA1_deltadeltacq <- read_csv(here("raw_data_analysis/data/norm_qpcr/motif_context_dependence/pTSA1_pPGK1_pSRO9_tTSA1_deltadeltacq_platesnorm_summarise.csv")) %>%
  mutate(mod_label = factor(UTR3,
                       levels = construct_to_label_dictionary_TSA1_RPS3$TSA1_UTR3,
                       labels = construct_to_label_dictionary_TSA1_RPS3$label),
         promoter = factor(promoter, levels = c("pTSA1","pPGK1","pSRO9")))

RPS3_deltadeltacq <- read_csv(here("raw_data_analysis/data/norm_qpcr/motif_context_dependence/pRPS3_pPGK1_pSRO9_tRPS3_deltadeltacq_platesnorm_summarise.csv")) %>%
  mutate(mod_label = factor(UTR3,
                       levels = construct_to_label_dictionary_TSA1_RPS3$RPS3_UTR3,
                       labels = construct_to_label_dictionary_TSA1_RPS3$label),
         promoter = factor(promoter, levels = c("pRPS3","pPGK1","pSRO9")))

construct_to_label_dictionary_PIR1 = tibble(construct = c("modG", "modF", "modE", "modD", "modC", "modA", "modB", "WT"), 
                                                 label = c("mod_NTNNN", "mod_ANNNN", "mod_ATNNN", "mod_ATHNH", "mod_ATNHH", "mod_ANHHH", "mod_NTHHH", "WT"),
                                                 PIR1_UTR3 = str_c("tPIR1_",construct))

PIR1_deltadeltacq <- read_csv(here("raw_data_analysis/data/norm_qpcr/motif_context_dependence/pPIR1_pPGK1_pSRO9_tPIR1_deltadeltacq_platesnorm_summarise.csv")) %>%
  mutate(mod_label = factor(UTR3,
                            levels = construct_to_label_dictionary_PIR1$PIR1_UTR3,
                            labels = construct_to_label_dictionary_PIR1$label),
         promoter = factor(promoter, levels = c("pPIR1","pPGK1","pSRO9")))
```

```{r calculate-fold-changes}
terminator_mod_ttest<- function(mod_label, deltadelta_cq, base_deltadelta_cq, base_label = "mod_NNN"){
  tidy(lm(deltadelta_cq ~ mod_label, data = tibble(mod_label = factor(c(mod_label,
                                                                        rep(base_label, 6)),
                                                                      levels = c(base_label,
                                                                                 mod_label[1])),
                                                    deltadelta_cq =c(deltadelta_cq,
                                                                     base_deltadelta_cq)))) %>%
  filter(term != "(Intercept)") %>%
  transmute(fold_change = 2^(-estimate), p.value)
}

TSA1_ttests <- TSA1_deltadeltacq %>%
  arrange(construct) %>%
  group_by(promoter) %>%
  mutate(base_deltadelta_cq = rep(deltadelta_cq[mod_label == "mod_NNN"], 7)) %>%
  group_by(promoter, mod_label) %>%
  summarise(terminator_mod_ttest(mod_label, deltadelta_cq, base_deltadelta_cq))

# split pPGK1_tRPS3 from rest of constructs as it is missing one bio_rep

RPS3_ttests_not_pPGK1 <- RPS3_deltadeltacq %>%
  filter(!(promoter == "pPGK1")) %>%
  arrange(construct) %>%
  group_by(promoter) %>%
  mutate(base_deltadelta_cq = rep(deltadelta_cq[mod_label == "mod_NNN"], 7)) %>%
  group_by(promoter, mod_label) %>%
  summarise(terminator_mod_ttest(mod_label, deltadelta_cq, base_deltadelta_cq))

RPS3_ttests_pPGK1_not_WT <- RPS3_deltadeltacq %>%
  filter(promoter == "pPGK1" & mod_label != "WT") %>%
  arrange(construct) %>%
  group_by(promoter) %>%
  mutate(base_deltadelta_cq = rep(deltadelta_cq[mod_label == "mod_NNN"], 6)) %>%
  group_by(promoter, mod_label) %>%
  summarise(terminator_mod_ttest(mod_label, deltadelta_cq, base_deltadelta_cq))

RPS3_ttests_pPGK1_WT <- terminator_mod_ttest(rep("WT", 5),
                                                           RPS3_deltadeltacq %>%
                                                             filter(promoter == "pPGK1" &
                                                                      mod_label == "WT") %>%
                                                             pull(deltadelta_cq),
                                                           RPS3_deltadeltacq %>%
                                                             filter(promoter == "pPGK1" &
                                                                      mod_label == "mod_NNN") %>%
                                                             pull(deltadelta_cq)) %>%
  mutate(promoter = "pPGK1", mod_label = factor("WT"))

RPS3_ttests <- RPS3_ttests_not_pPGK1 %>% 
  bind_rows(RPS3_ttests_pPGK1_not_WT) %>% 
  bind_rows(RPS3_ttests_pPGK1_WT)

PIR1_ttests <- PIR1_deltadeltacq %>%
  arrange(construct) %>%
  group_by(promoter) %>%
  mutate(base_deltadelta_cq = rep(deltadelta_cq[mod_label == "WT"], 8)) %>%
  group_by(promoter, mod_label) %>%
  summarise(terminator_mod_ttest(mod_label, deltadelta_cq, base_deltadelta_cq, base_label = "WT"))

combined_ttests <- TSA1_ttests %>%
  mutate(terminator = "tTSA1") %>%
  filter(mod_label != "mod_NNN") %>%
  bind_rows(RPS3_ttests %>%
              mutate(terminator = "tRPS3") %>%
              filter(mod_label != "mod_NNN")) %>%
  bind_rows(PIR1_ttests %>%
              mutate(terminator = "tPIR1") %>%
              filter(mod_label != "WT")) %>%
  mutate(p.adj = p.adjust(p.value, method = "fdr"))
```

```{r create-insertion-plot}
TSA1_deltadeltacq_plot <- ggplot(data = TSA1_deltadeltacq)+
  RNA_relative_abundance_figure_options +
  scale_colour_manual(values=RPS3_TSA1_colour_scheme) +
  theme(axis.text.y=element_text(colour=RPS3_TSA1_colour_scheme, face = "bold")) +
  labs(x ="Fold change in RNA abundance relative to tTSA1 mod_NNN", y = "") +
  facet_wrap(~promoter,ncol = 3) 

RPS3_deltadeltacq_plot <- ggplot(data = RPS3_deltadeltacq) +
  RNA_relative_abundance_figure_options +
  scale_colour_manual(values=RPS3_TSA1_colour_scheme) +
  theme(axis.text.y=element_text(colour=RPS3_TSA1_colour_scheme, face = "bold")) +
  labs(x ="Fold change in RNA abundance relative to tRPS3 mod_NNN", y = "") +
  facet_wrap(~promoter,ncol = 3) 

insertion_construct_displaytable <- 
  tableGrob(tibble("Terminator" = c("mod_NNN", "mod_NAA", "mod_NTN",
                                   "mod_HNH", "mod_HTH", "mod_NGG", "WT"), 
                   "Motif 1" = c("Random", "Random", "Random", 
                                 "HWNCATTWY", "HWNCATTWY", "Random", "NA"), 
                   "Motif 2" = c("Random", "ATATTC", "TGTAHMNTA", 
                                 "Random", "TGTAHMNTA", "GTATACCTA", "NA"), 
                   "Motif 3" = c("Random", "ATATTC", "Random", 
                                 "HWNCATTWY", "HWNCATTWY", "GTATACCTA", "NA")),
            rows = NULL,
            theme = ttheme_minimal(base_size=8,
                                   padding = unit(c(2, 2), "mm"),
                                   core=list(
                                     fg_params=list(col = c("black", "#C05558", "#5978BA", "#71519C", "#C288BB", "#7FBF74", "#6C6C6C",
                                                            "black", "black", "black", "#71519C", "#C288BB", "black", "#6C6C6C",
                                                            "black", "#C05558", "#5978BA", "black", "#C288BB", "#7FBF74", "#6C6C6C",
                                                            "black", "#C05558", "black", "#71519C", "#C288BB", "#7FBF74", "#6C6C6C"),
                                                    fontface = c(rep("bold",7), rep("plain", 21))))
            ))  %>%
  # the following code adds boxes around the table, row 1, and column 1
  gtable_add_grob(
    grobs = rectGrob(gp = gpar(fill = NA, lwd = 0.5)),
    t = 1, b = 8, l = 1, r = 4) %>%
  gtable_add_grob(
    grobs = rectGrob(gp = gpar(fill = NA, lwd = 0.5)),
    t = 1, b = 1, l = 1, r = 4) %>%
  gtable_add_grob(
    grobs = rectGrob(gp = gpar(fill = NA, lwd = 0.5)),
    t = 1, b = 8, l = 1, r = 1)

## print the table to see how it looks
grid.newpage()
grid.draw(insertion_construct_displaytable)

top_row_insertion_construct_plot <- 
  plot_grid(
    ggdraw() + 
      draw_image(image_read(here("raw_data_analysis/figures/terminator_construct_designs/RPS3_TSA1_motif_mod0_construct_design.png"))),
    insertion_construct_displaytable,
    ncol = 2)

insertion_construct_plot <- 
  plot_grid(
    top_row_insertion_construct_plot,
    RPS3_deltadeltacq_plot,
    TSA1_deltadeltacq_plot,
    ncol = 1,
    rel_heights = c(1,1,1),
    labels = c("A", "B", "C"))
```

```{r create-deletion-plot}

PIR1_deltadeltacq_plot <- ggplot(data = PIR1_deltadeltacq)+
  RNA_relative_abundance_figure_options +
  scale_colour_manual(values=PIR1_colour_scheme) +
  theme(axis.text.y=element_text(colour=PIR1_colour_scheme, face = "bold")) +
  labs(x ="Fold change in RNA abundance relative to tPIR1 mod_WT", y = "") +
  facet_wrap(~promoter,ncol = 3)

deletion_construct_displaytable <- 
  tableGrob(tibble("Terminator" = rev(c("mod_NTNNN", "mod_ANNNN", "mod_ATNNN", "mod_ATHNH", 
                                       "mod_ATNHH", "mod_ANHHH", "mod_NTHHH", "WT")), 
                   "Motif 1" = c("ATATTC", "Random", "ATATTC", 
                                 "ATATTC", "ATATTC", "ATATTC", "ATATTC", "Random"), 
                   "Motif 2" = c("TGTAHMNTA", "TGTAHMNTA", "Random", 
                                 "TGTAHMNTA", "TGTAHMNTA", "TGTAHMNTA", "Random", "TGTAHMNTA"), 
                   "Motif 3" = c("HWNCATTWY", "HWNCATTWY", "HWNCATTWY", 
                                 "Random", "HWNCATTWY", "Random", "Random", "Random"),
                   "Motif 4" = c("HWNCATTWY", "HWNCATTWY", "HWNCATTWY", 
                                 "HWNCATTWY", "Random", "Random", "Random", "Random"),
                   "Motif 5" = c("HWNCATTWY", "HWNCATTWY", "HWNCATTWY", 
                                 "HWNCATTWY", "HWNCATTWY", "Random", "Random", "Random")),
            rows = NULL,
            theme = ttheme_minimal(
              base_size=8,
              padding = unit(c(2, 2), "mm"),
              core=list(
                fg_params=list(col = c("#6C6C6C", "#C15659", "#5978BA", "#4EB0B5", "#D97F1D", "#71519C", "#968BC2", "#DD76A5",
                                       "black", "#C15659", "black", "black", "black", "black", "black", "#DD76A5",
                                       "black", "black", "#5978BA", "black", "black", "black", "#968BC2", "black",
                                       "black", "black", "black", "#4EB0B5", "black", "#71519C", "#968BC2", "#DD76A5",
                                       "black", "black", "black", "black", "#D97F1D", "#71519C", "#968BC2", "#DD76A5",
                                       "black", "black", "black", "black", "black", "#71519C", "#968BC2", "#DD76A5"),
                               fontface = c(rep("bold",8), rep("plain", 40))))
  )) %>%
  # the following code adds boxes aronud the table, row 1, and column 1
  gtable_add_grob(
    grobs = rectGrob(gp = gpar(fill = NA, lwd = 0.5)),
    t = 1, b = 9, l = 1, r = 6) %>%
  gtable_add_grob(
    grobs = rectGrob(gp = gpar(fill = NA, lwd = 0.5)),
    t = 1, b = 1, l = 1, r = 6) %>%
  gtable_add_grob(
    grobs = rectGrob(gp = gpar(fill = NA, lwd = 0.5)),
    t = 1, b = 9, l = 1, r = 1)

## print the table to see how it looks
grid.newpage()
grid.draw(deletion_construct_displaytable)

deletion_construct_plot <- 
  plot_grid(NULL, # create top margin above ggdraw; probably there is a better way
            ggdraw() + 
              draw_image(image_read(here("raw_data_analysis/figures/terminator_construct_designs/PIR1_motif_WT_construct_design.png")) 
              ),
            deletion_construct_displaytable,
            PIR1_deltadeltacq_plot,
            rel_heights = c(0.02, 0.4, 0.7, 1),
            ncol = 1,
            labels = c("A","","B"))
```            

```{r save-plots, eval=FALSE}
write_csv(combined_ttests,
          file = here("supplementary_data_chapter/data/motif_construct_ttests.csv"))

ggsave(filename = here("results_chapter/figures/insertion_constructs_design_and_qpcr.png"),
       insertion_construct_plot,
       width = fig_width_2column,
       height = 200,
       unit = "mm",
       dpi = fig_dpi)
       
ggsave(here("results_chapter/figures/tPIR1_design_and_qpcr.png"),
       deletion_construct_plot,
       width = fig_width_2column,
       height = 150,
       units = "mm",
       dpi = fig_dpi)
```