---
title: "Analysis of RT-qPCR data sets with two experimental replicates under different normalisation"
author: "Sam Haynes"
date: "22/07/2020"
output:
  html_document:
    toc: true
    toc_depth: 2
---
Comparing the normalistion of four qPCR datasets; pRPS3-tRPS3, pPGK1-tRPS3, pTSA1-tTSA1 and pPGK1-tTSA1, by three different normalisation genes; RPS3, PGK1, URA3.

```{r read_in_normalised_datasets, echo=FALSE, include=FALSE}
library(broom)
library(tidyverse)
library(here)
library(cowplot)

pPGK1_tRPS3_norm_mean <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pPGK1_tRPS3_n1_n2_norm_mean.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pPGK1_tRPS3_norm_median <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pPGK1_tRPS3_n1_n2_norm_median.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pPGK1_tRPS3_norm_RPS3 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pPGK1_tRPS3_n1_n2_norm_RPS3.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pPGK1_tRPS3_norm_URA3 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pPGK1_tRPS3_n1_n2_norm_URA3.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pPGK1_tRPS3_norm_PGK1 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pPGK1_tRPS3_n1_n2_norm_PGK1.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pRPS3_tRPS3_norm_median <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pRPS3_tRPS3_n1_n2_norm_median.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pRPS3_tRPS3_norm_mean <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pRPS3_tRPS3_n1_n2_norm_mean.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pRPS3_tRPS3_norm_RPS3 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pRPS3_tRPS3_n1_n2_norm_RPS3.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pRPS3_tRPS3_norm_URA3 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pRPS3_tRPS3_n1_n2_norm_URA3.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pRPS3_tRPS3_norm_PGK1 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pRPS3_tRPS3_n1_n2_norm_PGK1.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pPGK1_tTSA1_norm_mean <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pPGK1_tTSA1_n1_n2_norm_mean.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pPGK1_tTSA1_norm_median <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pPGK1_tTSA1_n1_n2_norm_median.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pPGK1_tTSA1_norm_RPS3 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pPGK1_tTSA1_n1_n2_norm_RPS3.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pPGK1_tTSA1_norm_URA3 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pPGK1_tTSA1_n1_n2_norm_URA3.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pPGK1_tTSA1_norm_PGK1 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pPGK1_tTSA1_n1_n2_norm_PGK1.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pTSA1_tTSA1_norm_mean <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pTSA1_tTSA1_n1_n2_norm_mean.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pTSA1_tTSA1_norm_median <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pTSA1_tTSA1_n1_n2_norm_median.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pTSA1_tTSA1_norm_RPS3 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pTSA1_tTSA1_n1_n2_norm_RPS3.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pTSA1_tTSA1_norm_URA3 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pTSA1_tTSA1_n1_n2_norm_URA3.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")

pTSA1_tTSA1_norm_PGK1 <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pTSA1_tTSA1_n1_n2_norm_PGK1.csv")) %>%
  group_by(construct, bio_rep, exp_rep, terminator, promoter) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop")
```

```{r run_linear_models, echo=FALSE, include=FALSE}
pTSA1_tTSA1_norm_mean_lm <- lm(delta_cq ~ exp_rep + construct, pTSA1_tTSA1_norm_mean)

pTSA1_tTSA1_norm_median_lm <- lm(delta_cq ~ exp_rep + construct, pTSA1_tTSA1_norm_median)

pTSA1_tTSA1_norm_PGK1_lm <- lm(delta_cq ~ exp_rep + construct, pTSA1_tTSA1_norm_PGK1)

pTSA1_tTSA1_norm_URA3_lm <- lm(delta_cq ~ exp_rep + construct, pTSA1_tTSA1_norm_URA3)

pTSA1_tTSA1_norm_RPS3_lm <- lm(delta_cq ~ exp_rep + construct, pTSA1_tTSA1_norm_RPS3)

pPGK1_tTSA1_norm_mean_lm <- lm(delta_cq ~ exp_rep + construct, pPGK1_tTSA1_norm_mean)

pPGK1_tTSA1_norm_median_lm <- lm(delta_cq ~ exp_rep + construct, pPGK1_tTSA1_norm_median)

pPGK1_tTSA1_norm_RPS3_lm <- lm(delta_cq ~ exp_rep + construct, pPGK1_tTSA1_norm_RPS3)

pPGK1_tTSA1_norm_URA3_lm <- lm(delta_cq ~ exp_rep + construct, pPGK1_tTSA1_norm_URA3)

pPGK1_tTSA1_norm_PGK1_lm <- lm(delta_cq ~ exp_rep + construct, pPGK1_tTSA1_norm_PGK1)

pRPS3_tRPS3_norm_mean_lm <- lm(delta_cq ~ exp_rep + construct, pRPS3_tRPS3_norm_mean)

pRPS3_tRPS3_norm_median_lm <- lm(delta_cq ~ exp_rep + construct, pRPS3_tRPS3_norm_median)

pRPS3_tRPS3_norm_RPS3_lm <- lm(delta_cq ~ exp_rep + construct, pRPS3_tRPS3_norm_RPS3)

pRPS3_tRPS3_norm_URA3_lm <- lm(delta_cq ~ exp_rep + construct, pRPS3_tRPS3_norm_URA3)

pRPS3_tRPS3_norm_PGK1_lm <- lm(delta_cq ~ exp_rep + construct, pRPS3_tRPS3_norm_PGK1)

pPGK1_tRPS3_norm_mean_lm <- lm(delta_cq ~ exp_rep + construct, pPGK1_tRPS3_norm_mean)

pPGK1_tRPS3_norm_median_lm <- lm(delta_cq ~ exp_rep + construct, pPGK1_tRPS3_norm_median)

pPGK1_tRPS3_norm_RPS3_lm <- lm(delta_cq ~ exp_rep + construct, pPGK1_tRPS3_norm_RPS3)

pPGK1_tRPS3_norm_URA3_lm <- lm(delta_cq ~ exp_rep + construct, pPGK1_tRPS3_norm_URA3)

pPGK1_tRPS3_norm_PGK1_lm <- lm(delta_cq ~ exp_rep + construct, pPGK1_tRPS3_norm_PGK1)

```

# Comparison of transcript abundance linear models 
Each qpcr data set normalised by each gene is fitted separately with construct and exp_rep as predicates.

```{r collate_lm_results, echo=FALSE}
model_r_squares <- tibble(
  ter_pro = c("pTSA1_tTSA1", "pTSA1_tTSA1", "pTSA1_tTSA1", "pTSA1_tTSA1", "pTSA1_tTSA1", "pPGK1_tTSA1", "pPGK1_tTSA1", "pPGK1_tTSA1", "pPGK1_tTSA1", "pPGK1_tTSA1", "pRPS3_tRPS3", "pRPS3_tRPS3", "pRPS3_tRPS3", "pRPS3_tRPS3", "pRPS3_tRPS3", "pPGK1_tRPS3", "pPGK1_tRPS3", "pPGK1_tRPS3", "pPGK1_tRPS3", "pPGK1_tRPS3"),
  norm_by = c("median", "mean", "PGK1", "URA3", "RPS3", "median", "mean", "RPS3", "URA3", "PGK1", "median", "mean", "RPS3", "URA3", "PGK1", "median", "mean", "RPS3", "URA3", "PGK1"),
  R_squared = c(summary(pTSA1_tTSA1_norm_median_lm)$r.squared,
                summary(pTSA1_tTSA1_norm_mean_lm)$r.squared,
                summary(pTSA1_tTSA1_norm_PGK1_lm)$r.squared,
                summary(pTSA1_tTSA1_norm_URA3_lm)$r.squared,
                summary(pTSA1_tTSA1_norm_RPS3_lm)$r.squared,
                summary(pPGK1_tTSA1_norm_median_lm)$r.squared,
                summary(pPGK1_tTSA1_norm_mean_lm)$r.squared,
                summary(pPGK1_tTSA1_norm_RPS3_lm)$r.squared,
                summary(pPGK1_tTSA1_norm_URA3_lm)$r.squared,
                summary(pPGK1_tTSA1_norm_PGK1_lm)$r.squared,
                summary(pRPS3_tRPS3_norm_median_lm)$r.squared,
                summary(pRPS3_tRPS3_norm_mean_lm)$r.squared,
                summary(pRPS3_tRPS3_norm_RPS3_lm)$r.squared,
                summary(pRPS3_tRPS3_norm_URA3_lm)$r.squared,
                summary(pRPS3_tRPS3_norm_PGK1_lm)$r.squared,
                summary(pPGK1_tRPS3_norm_median_lm)$r.squared,
                summary(pPGK1_tRPS3_norm_mean_lm)$r.squared,
                summary(pPGK1_tRPS3_norm_RPS3_lm)$r.squared,
                summary(pPGK1_tRPS3_norm_URA3_lm)$r.squared,
                summary(pPGK1_tRPS3_norm_PGK1_lm)$r.squared))

arrange(model_r_squares, ter_pro, desc(R_squared))

model_r_coefficients <- tidy(pTSA1_tTSA1_norm_PGK1_lm) %>%
  mutate(ter_pro = "pTSA1_tTSA1", norm_by = "PGK1") %>%
  bind_rows(tidy(pTSA1_tTSA1_norm_URA3_lm) %>%
  mutate(ter_pro = "pTSA1_tTSA1", norm_by = "URA3")) %>%
  bind_rows(tidy(pTSA1_tTSA1_norm_RPS3_lm) %>%
  mutate(ter_pro = "pTSA1_tTSA1", norm_by = "RPS3")) %>%
  bind_rows(tidy(pPGK1_tTSA1_norm_RPS3_lm) %>%
  mutate(ter_pro = "pPGK1_tTSA1", norm_by = "RPS3")) %>%
  bind_rows(tidy(pPGK1_tTSA1_norm_URA3_lm) %>%
  mutate(ter_pro = "pPGK1_tTSA1", norm_by = "URA3")) %>%
  bind_rows(tidy(pPGK1_tTSA1_norm_PGK1_lm) %>%
  mutate(ter_pro = "pPGK1_tTSA1", norm_by = "PGK1")) %>%
  bind_rows(tidy(pRPS3_tRPS3_norm_RPS3_lm) %>%
  mutate(ter_pro = "pRPS3_tRPS3", norm_by = "RPS3")) %>%
  bind_rows(tidy(pRPS3_tRPS3_norm_URA3_lm) %>%
  mutate(ter_pro = "pRPS3_tRPS3", norm_by = "URA3")) %>%
  bind_rows(tidy(pRPS3_tRPS3_norm_PGK1_lm) %>%
  mutate(ter_pro = "pRPS3_tRPS3", norm_by = "PGK1")) %>%
  bind_rows(tidy(pPGK1_tRPS3_norm_RPS3_lm) %>%
  mutate(ter_pro = "pPGK1_tRPS3", norm_by = "RPS3")) %>%
  bind_rows(tidy(pPGK1_tRPS3_norm_URA3_lm) %>%
  mutate(ter_pro = "pPGK1_tRPS3", norm_by = "URA3")) %>%
  bind_rows(tidy(pPGK1_tRPS3_norm_PGK1_lm) %>%
  mutate(ter_pro = "pPGK1_tRPS3", norm_by = "PGK1")) %>%
  bind_rows(tidy(pPGK1_tRPS3_norm_mean_lm) %>%
  mutate(ter_pro = "pPGK1_tRPS3", norm_by = "mean")) %>%
  bind_rows(tidy(pRPS3_tRPS3_norm_mean_lm) %>%
  mutate(ter_pro = "pRPS3_tRPS3", norm_by = "mean")) %>%
  bind_rows(tidy(pPGK1_tTSA1_norm_mean_lm) %>%
  mutate(ter_pro = "pPGK1_tTSA1", norm_by = "mean")) %>%
  bind_rows(tidy(pTSA1_tTSA1_norm_mean_lm) %>%
  mutate(ter_pro = "pTSA1_tTSA1", norm_by = "mean")) %>%
  bind_rows(tidy(pTSA1_tTSA1_norm_median_lm) %>%
  mutate(ter_pro = "pTSA1_tTSA1", norm_by = "median")) %>%
  bind_rows(tidy(pPGK1_tTSA1_norm_median_lm) %>%
  mutate(ter_pro = "pPGK1_tTSA1", norm_by = "median")) %>%
  bind_rows(tidy(pPGK1_tRPS3_norm_median_lm) %>%
  mutate(ter_pro = "pTSA1_tTSA1", norm_by = "median")) %>%
  bind_rows(tidy(pRPS3_tRPS3_norm_median_lm) %>%
  mutate(ter_pro = "pTSA1_tTSA1", norm_by = "median"))

ggplot(model_r_coefficients) +
  geom_point(aes(x=term, y=estimate, shape = norm_by, colour = (p.value < 0.05)), position = position_jitter(width = 0.1)) +
  facet_wrap(~factor(ter_pro, levels =c("pRPS3_tRPS3", "pTSA1_tTSA1", "pPGK1_tRPS3", "pPGK1_tTSA1"))) + 
  theme_cowplot() +
  theme(axis.text.x = element_text(angle = 90), panel.grid.major.y = element_line(size = 0.1)) +
  labs(x = "", y = "Coefficient")

model_r_coefficients %>%
  group_by(norm_by) %>%
  summarise(no_sig_coef = sum(p.value < 0.05))
```