---
title: "Comparison of hlife predicted abundance changes and qPCR results"
output: html_document
---
Compares the predicted motif effect from the half life model to new qPCR data measure construct abundance. Creates the summary figure qPCR_model_coef_and_pred_vs_exp_abund.png used in the results section in the paper.

Requires train_half_life_model.R to be ran first

```{r load_data}
library(here)
library(dplyr)
library(tibble)
library(stringr)
library(readr)
library(latex2exp)

 # set default theme for graphics
source(here("raw_data_analysis/code/shared_figure_formatting.R"))

construct_to_motif_dictionary_PIR1 <- tibble(construct = 
                                                    rep(c("WT", "modA", "modB", "modC", "modD", "modE", "modF", "modG"), each = 3), 
                                                  Motif = rep(c("ATATTC","TGTAHMNTA","HWNCATTWY"), times = 8), 
                                                   count = c(1,1,3,
                                                             1,0,3,
                                                             0,1,3,
                                                             1,1,2,
                                                             1,1,2,
                                                             1,1,0,
                                                             1,0,0,
                                                             0,1,0))

construct_to_motif_dictionary_TSA1_RPS3 <- tibble (construct = 
                                                rep(c("WT", "mod0", "modA", "modB", "modC", "modD", "modE"), times = 4), 
                                              Motif = 
                                                rep(c("ATATTC", "GTATACCTA","TGTAHMNTA","HWNCATTWY"), each = 7), 
                                              count = c(0,0,0,2,0,0,0,
                                                        0,0,0,0,2,0,0,
                                                        0,0,1,0,0,0,1,
                                                        0,0,0,0,0,2,2))
 
hlife_coefficients_TSA1_RPS3 <- read_csv(here("./raw_data_analysis/data/chan_motif_coefficients_with_error.csv")) %>% 
  inner_join(construct_to_motif_dictionary_TSA1_RPS3) %>%
  group_by(construct) %>%
  mutate(predict_motif_error = sum(count * std.error)) %>%
  group_by(construct, predict_motif_error) %>%
  summarise(predict_motif_effect = sum(count * Coefficient), .groups = "drop")

hlife_coefficients_PIR1 <- read_csv(here("./raw_data_analysis/data/chan_motif_coefficients_with_error.csv")) %>% 
  inner_join(construct_to_motif_dictionary_PIR1) %>%
  group_by(construct) %>%
  mutate(predict_motif_error = sum(count * std.error)) %>%
  group_by(construct, predict_motif_error) %>%
  summarise(predict_motif_effect = sum(count * Coefficient), .groups = "drop") %>%
  mutate(predict_motif_effect = predict_motif_effect - predict_motif_effect[construct == "WT"])

```

```{r normalise-qPCR-counts-to-control-construct}

# function to calculate mean cq value for control construct 
mean_control <- function(cq_value, construct, control = "mod0"){
  cq_value[construct == {{control}}] %>% mean()
}

pRPS3_pPGK1_pSRO9_tRPS3_norm_mean <- read_csv(here("./raw_data_analysis/data/norm_qpcr/motif_context_dependence/pRPS3_pPGK1_pSRO9_tRPS3_deltacq_platesnorm_summarise.csv")) %>%
  filter( target_id == "mCh-7") %>%
  group_by(promoter) %>%
  mutate(mod0_delta_cq = mean_control(deltacq, construct)) %>%
  group_by(construct, promoter) %>%
  mutate( delta_delta_cq = deltacq - mod0_delta_cq) %>%
  ungroup() 

pTSA1_pPGK1_pSRO9_tTSA1_norm_mean <- read_csv(here("./raw_data_analysis/data/norm_qpcr/motif_context_dependence/pTSA1_pPGK1_pSRO9_tTSA1_deltacq_platesnorm_summarise.csv")) %>%
  filter( target_id == "mCh-7") %>%
  group_by(promoter) %>%
  mutate(mod0_delta_cq = mean_control(deltacq, construct)) %>%
  group_by(construct, promoter) %>%
  mutate( delta_delta_cq = deltacq - mod0_delta_cq) %>%
  ungroup() 

pPIR1_pPGK1_pSRO9_tPIR1_norm_mean <- read_csv(here("./raw_data_analysis/data/norm_qpcr/motif_context_dependence/pPIR1_pPGK1_pSRO9_tPIR1_deltacq_platesnorm_summarise.csv")) %>%
  filter( target_id == "mCh-7") %>%
  group_by(promoter) %>%
  mutate(mod0_delta_cq = mean_control(deltacq, construct, "WT")) %>%
  group_by(construct, promoter) %>%
  mutate( delta_delta_cq = deltacq - mod0_delta_cq) %>%
  ungroup() 

combined_pred_vs_actual_abund_TSA1_RPS3 <- pRPS3_pPGK1_pSRO9_tRPS3_norm_mean %>%
  bind_rows(pTSA1_pPGK1_pSRO9_tTSA1_norm_mean)

combined_pred_vs_actual_abund_TSA1_RPS3 %>%
  group_by(promoter,terminator, construct) %>%
  summarise(delta_delta_cq = median(delta_delta_cq)) %>%
  inner_join(hlife_coefficients_TSA1_RPS3) %>%
  group_by(promoter, terminator) %>%
  mutate(r_squared = cor(predict_motif_effect, delta_delta_cq)^2) %>%
  ungroup()

```

```{r plot_pred_vs_actual}
promoter_dictionary_TSA1_RPS3 <- tibble( pro = c("pPGK1", "Native", "pSRO9", "pPGK1", "Native", "pSRO9"), promoter = c("pPGK1", "pTSA1", "pSRO9", "pPGK1", "pRPS3", "pSRO9"))

promoter_dictionary_PIR1 <- tibble( pro = c("pPGK1", "Native", "pSRO9"), promoter = c("pPGK1", "pPIR1", "pSRO9"))

# calculate correlation

r_cor_data_TSA1_RPS3 <- combined_pred_vs_actual_abund_TSA1_RPS3 %>% 
  group_by(construct, terminator, promoter) %>% 
  summarise(delta_delta_cq = mean(delta_delta_cq), .groups = "drop") %>%
  inner_join(hlife_coefficients_TSA1_RPS3) %>% 
  group_by(terminator, promoter) %>% 
  summarise(r_cor = cor(-delta_delta_cq, predict_motif_effect), .groups = "drop") %>%
  mutate(r_cor_label = paste(TeX(paste0("R = ", signif(r_cor,digits = 3))))) %>% 
  inner_join(promoter_dictionary_TSA1_RPS3)

r_cor_data_PIR1 <- pPIR1_pPGK1_pSRO9_tPIR1_norm_mean %>% 
  group_by(construct, terminator, promoter) %>% 
  summarise(delta_delta_cq = mean(delta_delta_cq), .groups = "drop") %>%
  inner_join(hlife_coefficients_PIR1) %>% 
  group_by(terminator, promoter) %>% 
  summarise(r_cor = cor(-delta_delta_cq, predict_motif_effect), .groups = "drop") %>%
  mutate(r_cor_label = paste(TeX(paste0("R = ", signif(r_cor,digits = 3))))) %>% 
  inner_join(promoter_dictionary_PIR1)


combined_pred_vs_actual_plot_data_TSA1_RPS3 <- combined_pred_vs_actual_abund_TSA1_RPS3 %>%
  inner_join(promoter_dictionary_TSA1_RPS3) %>%
  group_by(construct, terminator, pro) %>%
  summarise(mean_delta_delta_cq = mean(delta_delta_cq), sd_ddcq = sd(delta_delta_cq), .groups = "drop") %>%
  inner_join(hlife_coefficients_TSA1_RPS3) %>% 
  inner_join(construct_to_label_dictionary_TSA1_RPS3)

pred_vs_actual_plot_data_PIR1 <- pPIR1_pPGK1_pSRO9_tPIR1_norm_mean %>%
  inner_join(promoter_dictionary_PIR1) %>% 
  group_by(construct, terminator, pro) %>%
  summarise(mean_delta_delta_cq = mean(delta_delta_cq), sd_ddcq = sd(delta_delta_cq), .groups = "drop") %>%
  inner_join(hlife_coefficients_PIR1) %>%
  inner_join(construct_to_label_dictionary_PIR1)

pred_vs_abundance_figure_options <- list(
  geom_diagline(),
  geom_point(aes(predict_motif_effect, -mean_delta_delta_cq, colour = label), show.legend = FALSE),
   geom_errorbarh(aes(y = -mean_delta_delta_cq, xmax = predict_motif_effect + predict_motif_error, xmin = predict_motif_effect - predict_motif_error, colour = label)),
 geom_errorbar(aes(predict_motif_effect, ymax = -mean_delta_delta_cq + sd_ddcq, ymin = -mean_delta_delta_cq - sd_ddcq, colour = label)),
  facet_grid(terminator~pro),
  labs(x="", y="", colour = "Construct"),
 theme(axis.title.y = element_text(hjust = 1.1), strip.text.x = element_text(vjust = 0.95))
)



pred_vs_abundance_RPS3_TSA1 <- ggplot(combined_pred_vs_actual_plot_data_TSA1_RPS3 %>% filter(terminator %in% c("tRPS3", "tTSA1"))) + 
  pred_vs_abundance_figure_options +
  coord_fixed(ratio = 1 , xlim = c(-2.5, 1.5) ,ylim = c(-2.5, 1.5)) +
  scale_colour_manual("Terminator",
                      values = RPS3_TSA1_colour_scheme,
                      guide = guide_legend(reverse=TRUE)) + 
  geom_text(aes(label = r_cor_label), data = r_cor_data_TSA1_RPS3, 
            x = -0.05, y = 1.05, 
            size = text_cor_size, hjust = 1, vjust = 0) +
  labs(y=TeX("Reporter construct $log_2$ fold change in RNA abundance"))

pred_vs_abundance_PIR1 <- ggplot(pred_vs_actual_plot_data_PIR1) + 
  pred_vs_abundance_figure_options +
  coord_fixed(ratio = 1 , xlim = c(-1, 1.2) ,ylim = c(-1, 1.2)) +
  scale_colour_manual("Terminator",
                      values = PIR1_colour_scheme,
                      guide = guide_legend(reverse=TRUE)) + 
  geom_text(aes(label = r_cor_label), 
            data = r_cor_data_PIR1, 
            x = 0.95, y = -0.95, 
            size = text_cor_size, hjust = 1, vjust = 0) +
  scale_x_continuous(breaks = c(-1,0,1)) +
  scale_y_continuous(breaks = c(-1,0,1)) +
  labs(x=TeX("Predicted $log_2$ fold change in RNA half-life"))


# load figure panel with coefficients.
# this is an unpleasant way of doing it; we should replace somehow.
load(here("raw_data_analysis/data/motif_multi_context_coefficient.Rdata"))


pred_vs_abundance_combined <- plot_grid(pred_vs_abundance_RPS3_TSA1,
           pred_vs_abundance_PIR1,
           individual_linear_model_coefficients_points,
           ncol = 1,
           rel_heights = c(1.58, 1, 1.14),
           align = "v", axis= "lr",
           labels = c("A","","B"))

```

```{r save-results, eval = FALSE}
# combine with motif_multi_context_coefficient figure to make two panel image

ggsave(pred_vs_abundance_combined, 
       file = here("results_chapter/figures/qPCR_model_coef_and_pred_vs_exp_abund.png"), 
       width = fig_width_2column, 
       height = 210,
       units = "mm",
       dpi = fig_dpi)
```
