---
title: "Linear model comparing motif performance in different promoters"
output: html_document
---


```{r import_data}
library(here)

tTSA1_pTSA1_norm_qpcr <- read_csv(here("raw_data_analysis/data/norm_qpcr/pTSA1_tTSA1_n1_n2_norm.csv"))

tPGK1_pTSA1_norm_qpcr <- read_csv(here("raw_data_analysis/data/norm_qpcr/pPGK1_tTSA1_n1_n2_norm.csv"))

tRPS3_pRPS3_norm_qpcr <- read_csv(here("raw_data_analysis/data/norm_qpcr/pRPS3_tRPS3_n1_n2_norm.csv"))

tPGK1_pRPS3_norm_qpcr <- read_csv(here("raw_data_analysis/data/norm_qpcr/pPGK1_tRPS3_n1_n2_norm.csv"))

combined_data <- tTSA1_pTSA1_norm_qpcr %>%
  bind_rows(tPGK1_pTSA1_norm_qpcr) %>%
  bind_rows(tRPS3_pRPS3_norm_qpcr) %>%
  bind_rows(tPGK1_pRPS3_norm_qpcr) %>%
  unite(experiment, promoter, terminator, remove = FALSE)
```

```{r run_individual_linear_models}
summary(lm(delta_cq ~ construct + exp_rep, tTSA1_pTSA1_norm_qpcr))

summary(lm(delta_cq ~ construct + exp_rep, tPGK1_pTSA1_norm_qpcr))

summary(lm(delta_cq ~ construct + exp_rep, tRPS3_pRPS3_norm_qpcr))

summary(lm(delta_cq ~ construct + exp_rep, tPGK1_pRPS3_norm_qpcr))

```

```{r run_promoter_interaction_effects_linear_model}
summary(lm(delta_cq ~ terminator + construct + promoter, combined_data))
summary(lm(delta_cq ~ terminator + construct*promoter, combined_data))
summary(lm(delta_cq ~ construct*terminator + promoter, combined_data))
summary(lm(delta_cq ~ construct*terminator + construct*promoter, combined_data))
step(lm(delta_cq ~ terminator + construct + promoter, combined_data), delta_cq ~ construct*terminator + construct*promoter)
```

