---
title: "Poly(A) Site Usage Plot"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(readr)
library(tidyr)
library(dplyr)
library(extrafont)
library(purrr)
library(cowplot)
library(stringr)
library(ggtext)
library(glue)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
source(here("raw_data_analysis/code/shared_figure_formatting.R"))
```

```{r definitions}
genomic_gene_dictionary <- tibble(construct_name = c("chrXIII", "chrIII", "chrXIV"),
                                  promoter = c("pTSA1", "pPGK1", "pRPS3"),
                                  terminator = c("tTSA1", "tPGK1", "tRPS3"),
                                  mod = "genomic")

construct_stop_codon_dictionary <- read_csv(here("raw_data_analysis/data/rna_seq/gene_of_interest_stop_codons"))
```

```{r functions}
# reads in the polyA reads bed file outputted from the
# find_polyA_site.sh bash script in the nextflow_paired_reads_pipeline
# github repo. 
# For each sample file the function expects reads from three genomic genes:
# PGK1, RPS3 and TSA1 (used for normalisation), and two plasmid genes:
# URA3 and the construct of interest.
# The three genomic genes are on different chromosomes so mapped reads 
# are easily differentiated using the first column of the bed file
# The two plasmid genes are mapped to the same construct and are differentiated
# by the read_end position: read_end > 3500 -> URA3 , read_end < 3500 ->
# construct
load_polyA_reads <- function(filename) {
  full_bed_tibble<- read_tsv(filename,
                        col_names = c("construct_name", "chromStart", "read_end", 
                                      "name", "score", "strand", "thickStart",
                                      "thickEnd", "itemRgb", "blockCount",
                                      "blockSizes", "blockStarts")) 
  if(nrow(full_bed_tibble) > 0){
    # label reads mapped to construct of interest according to plasmid name (separating URA3 genes with by read end position)
    plasmid_construct_reads <- full_bed_tibble %>%
      filter(str_detect(construct_name, "mCherry")) %>%
      select(construct_name,read_end) %>%
      mutate(terminator = str_extract(construct_name, "t[A-Z0-9]+")) %>%
      mutate(promoter = str_extract(construct_name, "p[A-Z0-9]+")) %>%
      mutate(mod = str_extract(construct_name, "[a-zA-Z0-9]+$")) %>%
      mutate(sample = str_extract(filename, "(?<=/)[ABEdt0-9]+(?=_)")) %>%
      mutate(URA3 = (read_end > 3500))
    
    # label reads mapped to genomic genes according to chromosome
    genomic_reads <- full_bed_tibble %>%
      filter(!str_detect(construct_name, "mCherry")) %>%
      select(construct_name,read_end) %>%
      inner_join(genomic_gene_dictionary) %>%
      mutate(sample = str_extract(filename, "(?<=/)[ABEdt0-9]+(?=_)")) %>%
      mutate(URA3 = FALSE)
    
    bind_rows(plasmid_construct_reads, genomic_reads) 
  }
  else{NULL}
}

# for nucleotides without count data fill with 0 or value of last nucleotide with count data

fill_missing_nucleotide_data <- function(nucleotide_with_known_counts, empty_full_plasmid){
  # if first nucleotide has no entry, make a cumulative count 0 entry
  first_entry <- nucleotide_with_known_counts %>%
    filter(read_end == min(empty_full_plasmid$read_end))
  
  if(nrow(first_entry) == 0){
    nucleotide_with_known_counts <- nucleotide_with_known_counts[1,] %>%
      mutate(read_end = min(empty_full_plasmid$read_end),
             cumulative_counts = 0,
             rel_cumulative_counts = 0) %>%
      bind_rows(nucleotide_with_known_counts)
  }
  
  
  empty_full_plasmid %>%
    filter(construct_name == nucleotide_with_known_counts %>% pull(construct_name) %>% unique) %>%
  left_join(nucleotide_with_known_counts) %>%
  fill(read_end, terminator, promoter, mod, sample, URA3, cumulative_counts, rel_cumulative_counts, .direction = "down")
}

calc_polyA_site_usage <- function(polyA_count_data, polyA_site_position){
  total_counts_pre_polyA <- polyA_count_data %>%
    filter(read_end == polyA_site_position) %>%
    pull(cumulative_counts)
    
  
  total_counts_post_polyA <- polyA_count_data %>%
    filter(read_end == max(read_end)) %>%
    pull(cumulative_counts)
  
  tibble(sample = unique(polyA_count_data$sample), mod = unique(polyA_count_data$mod), pre_polyA_site_count_ratio = total_counts_pre_polyA / total_counts_post_polyA)
}
```

```{r load_polyA_reads, warnings = FALSE, message = FALSE, include=FALSE}
all_QuantSeq_PolyA_read_files <- list.files(path = here("raw_data_analysis/data/rna_seq/construct_polyA_bam/QuantSeq/"), pattern = ".bed$", recursive = TRUE, full.names = TRUE)

all_5PSeq_PolyA_read_files <- list.files(path = here("raw_data_analysis/data/rna_seq/construct_polyA_bam/5PSeq/"), pattern = ".bed$", recursive = TRUE, full.names = TRUE)

full_5PSeq_PolyA_reads <- all_5PSeq_PolyA_read_files %>%
  lapply(load_polyA_reads) %>%
  purrr::reduce(bind_rows)

full_QuantSeq_PolyA_reads <- all_QuantSeq_PolyA_read_files %>%
  lapply(load_polyA_reads) %>%
  purrr::reduce(bind_rows)

```


```{r calculate-cumulative-distibution, include=FALSE}

full_QuantSeq_polyA_reads_from_stop_codon_TSA1_PGK1 <- full_QuantSeq_PolyA_reads %>%
  filter(promoter %in% c("pTSA1", "pPGK1")) %>%
  inner_join(construct_stop_codon_dictionary) %>%
  mutate(read_end = read_end - stop_codon_pos) %>%
  filter(read_end > 0, read_end < 170)

full_QuantSeq_polyA_reads_from_stop_codon_RPS3_only <-full_QuantSeq_PolyA_reads %>%
  filter(promoter == "pRPS3") %>%
  inner_join(construct_stop_codon_dictionary) %>%
  mutate(read_end = read_end - stop_codon_pos) %>%
  filter(read_end > 0, read_end < 100)

full_QuantSeq_polyA_reads_from_stop_codon <- full_QuantSeq_polyA_reads_from_stop_codon_TSA1_PGK1 %>%
  bind_rows(full_QuantSeq_polyA_reads_from_stop_codon_RPS3_only)

full_5PSeq_polyA_reads_from_stop_codon_TSA1_PGK1_good_samples <- full_5PSeq_PolyA_reads %>%
  filter(promoter %in% c("pTSA1", "pPGK1"), !sample %in% c("12dt", "14dt", "16dt")) %>%
  inner_join(construct_stop_codon_dictionary) %>%
  mutate(read_end = read_end - stop_codon_pos) %>%
  filter(read_end > 0, read_end < 170)

full_5PSeq_polyA_reads_from_stop_codon_RPS3_only_good_samples <- full_5PSeq_PolyA_reads %>%
  filter(promoter == "pRPS3", !sample %in% c("12dt", "14dt", "16dt")) %>%
  inner_join(construct_stop_codon_dictionary) %>%
  mutate(read_end = read_end - stop_codon_pos) %>%
  filter(read_end > 0, read_end < 100)

full_5PSeq_polyA_reads_from_stop_codon <- full_5PSeq_polyA_reads_from_stop_codon_TSA1_PGK1_good_samples %>%
  bind_rows(full_5PSeq_polyA_reads_from_stop_codon_RPS3_only_good_samples)


full_QuantSeq_cumulative_polyA_reads <- full_QuantSeq_polyA_reads_from_stop_codon %>%
  group_by(construct_name,read_end, terminator, promoter, mod,sample, URA3) %>%
  summarise(read_count = n()) %>%
  arrange(construct_name, read_end) %>%
  group_by(construct_name, URA3, sample) %>%
  mutate(cumulative_counts = cumsum(read_count), 
         total_counts = sum(read_count),
         rel_counts = read_count / total_counts,
         rel_cumulative_counts = cumulative_counts / total_counts)

full_5PSeq_cumulative_polyA_reads <- full_5PSeq_polyA_reads_from_stop_codon %>%
  group_by(construct_name,read_end, terminator, promoter, mod,sample, URA3) %>%
  summarise(read_count = n()) %>%
  arrange(construct_name, read_end) %>%
  group_by(construct_name, URA3, sample) %>%
  mutate(cumulative_counts = cumsum(read_count), 
         total_counts = sum(read_count),
         rel_counts = read_count / total_counts,
         rel_cumulative_counts = cumulative_counts / total_counts)

empty_full_length_QuantSeq_plasmids <- tibble(construct_name = rep(full_QuantSeq_cumulative_polyA_reads %>% pull(construct_name) %>% unique(), each = 171), 
                                              read_end = rep(0:170,18))

empty_full_length_5PSeq_plasmids <- tibble(construct_name = rep(full_5PSeq_cumulative_polyA_reads %>% pull(construct_name) %>% unique(), each = 171), 
                                              read_end = rep(0:170,10))


full_length_QuantSeq_plasmids_cumulative_polyA_reads <- full_QuantSeq_cumulative_polyA_reads %>%
  select(-read_count, - total_counts) %>%
  group_by(construct_name, sample, URA3) %>%
  do(fill_missing_nucleotide_data(., empty_full_length_QuantSeq_plasmids)) %>%
  inner_join(construct_to_label_dictionary_TSA1_RPS3, by = c("mod" = "construct")) %>%
  mutate(label = factor(label, levels = construct_to_label_dictionary_TSA1_RPS3$label),
         promoter = factor(promoter, levels = c("pPGK1", "pRPS3", "pTSA1")))

full_length_5PSeq_plasmids_cumulative_polyA_reads <- full_5PSeq_cumulative_polyA_reads %>%
  select(-read_count, - total_counts) %>%
  group_by(construct_name, sample, URA3) %>%
  do(fill_missing_nucleotide_data(., empty_full_length_5PSeq_plasmids)) %>%
  inner_join(construct_to_label_dictionary_TSA1_RPS3, by = c("mod" = "construct")) %>%
  mutate(label = factor(label, levels = construct_to_label_dictionary_TSA1_RPS3$label))

full_length_QuantSeq_genomic_cumulative_polyA_reads <- full_QuantSeq_cumulative_polyA_reads %>%
  select(-read_count, - total_counts) %>%
  group_by(construct_name, sample) %>%
  do(fill_missing_nucleotide_data(., empty_full_length_QuantSeq_plasmids)) %>%
  filter(mod == "genomic")

full_length_5PSeq_genomic_cumulative_polyA_reads <- full_5PSeq_cumulative_polyA_reads %>%
  select(- read_count, - total_counts) %>%
  group_by(construct_name, sample) %>%
  do(fill_missing_nucleotide_data(., empty_full_length_5PSeq_plasmids)) %>%
  filter(mod == "genomic")

```

```{r plot_QC_cumulative_graph}
## Create 5PSeq QC cumulative plots by comparing genomic RPS3, PGK1 and TSA1 terminators across samples

full_length_QuantSeq_plasmids_cumulative_QC <- full_QuantSeq_cumulative_polyA_reads %>%
  filter(mod == "genomic") %>%
  select(-read_count, - total_counts) %>%
  group_by(construct_name, sample, URA3) %>%
  do(fill_missing_nucleotide_data(., empty_full_length_QuantSeq_plasmids))

genomic_QuantSeq_PGK1_cumulative_QC <- ggplot(full_length_QuantSeq_plasmids_cumulative_QC %>%
         filter(promoter == "pPGK1")) +
  geom_step(aes(x = read_end, y = rel_cumulative_counts, colour = sample)) +
  labs(x="", y="Fraction of Reads", title = "QuantSeq \n Genomic PGK1 Poly(A) sites") +
  lims(x = c(70,170)) +
  guides(colour = FALSE)

genomic_QuantSeq_TSA1_cumulative_QC <- ggplot(full_length_QuantSeq_plasmids_cumulative_QC %>%
         filter(promoter == "pTSA1")) +
  geom_step(aes(x = read_end, y = rel_cumulative_counts, colour = sample)) +
  labs(x="", y="Fraction of Reads", title = "Genomic TSA1 Poly(A) sites") +
  lims(x = c(80,120)) +
  guides(colour = FALSE)

genomic_QuantSeq_RPS3_cumulative_QC <- ggplot(full_length_QuantSeq_plasmids_cumulative_QC %>%
         filter(promoter == "pRPS3")) +
  geom_step(aes(x = read_end, y = rel_cumulative_counts, colour = sample)) +
  labs(x="", y="Fraction of Reads", title = "Genomic RPS3 Poly(A) sites") +
  lims(x = c(30,80)) +
  guides(colour = FALSE)

genomic_QuantSeq_combined_cumulative_QC <- plot_grid(genomic_QuantSeq_PGK1_cumulative_QC,
          genomic_QuantSeq_TSA1_cumulative_QC,
          genomic_QuantSeq_RPS3_cumulative_QC,
          get_legend(genomic_QuantSeq_PGK1_cumulative_QC +
                       guides(colour = guide_legend(nrow=3)) +
                                theme(legend.justification = "centre",
                                      legend.box.margin = margin(),
                                      legend.box = "vertical")),
          ncol = 1,
          rel_heights = c(1,1,1,0.7))

## Create 5PSeq QC cumulative plots

full_length_5PSeq_plasmids_cumulative_polyA_reads_genomic <- full_5PSeq_cumulative_polyA_reads %>%
  filter(mod == "genomic") %>%
  select(-read_count, - total_counts) %>%
  group_by(construct_name, sample, URA3) %>%
  do(fill_missing_nucleotide_data(., empty_full_length_5PSeq_plasmids))

genomic_5PSeq_PGK1_cumulative_QC <- ggplot(full_length_5PSeq_plasmids_cumulative_polyA_reads_genomic %>%
         filter(promoter == "pPGK1")) +
  geom_step(aes(x = read_end, y = rel_cumulative_counts, colour = sample)) +
  labs(x="", y="Fraction of Reads", title = "5PSeq \n Genomic PGK1 Poly(A) sites") +
  lims(x = c(70,170)) +
  guides(colour = FALSE)

genomic_5PSeq_RPS3_cumulative_QC <- ggplot(full_length_5PSeq_plasmids_cumulative_polyA_reads_genomic %>%
         filter(promoter == "pRPS3")) +
  geom_step(aes(x = read_end, y = rel_cumulative_counts, colour = sample)) +
  labs(x="", y="Fraction of Reads", title = "Genomic RPS3 Poly(A) sites") +
  lims(x = c(30,80)) +
  guides(colour = "none")

genomic_5PSeq_TSA1_cumulative_QC <- ggplot(full_length_5PSeq_plasmids_cumulative_polyA_reads_genomic %>%
         filter(promoter == "pTSA1")) +
  geom_step(aes(x = read_end, y = rel_cumulative_counts, colour = sample)) +
  labs(x="", y="Fraction of Reads", title = "Genomic TSA1 Poly(A) sites") +
  lims(x = c(80,120)) +
  guides(colour = "none")

genomic_5PSeq_combined_cumulative_QC <- plot_grid(genomic_5PSeq_PGK1_cumulative_QC,
          genomic_5PSeq_RPS3_cumulative_QC,
          genomic_5PSeq_TSA1_cumulative_QC,
          get_legend(genomic_5PSeq_PGK1_cumulative_QC +
                       guides(colour = guide_legend(nrow=2)) +
                                theme(legend.justification = "centre",
                                      legend.box.margin = margin(),
                                      legend.box = "vertical")),
          ncol = 1,
          rel_heights = c(1,1,1,0.7))

genomic_5PSeq_and_QuantSeq_combined_cumulative_QC <- plot_grid(genomic_5PSeq_PGK1_cumulative_QC, genomic_QuantSeq_PGK1_cumulative_QC,
          genomic_5PSeq_RPS3_cumulative_QC, genomic_QuantSeq_RPS3_cumulative_QC,
          genomic_5PSeq_TSA1_cumulative_QC, genomic_QuantSeq_TSA1_cumulative_QC,
          ncol = 2)
```

```{r output-polyA-QC-plot, eval = FALSE}

ggsave2(here("supplementary_data_chapter/figures/polya_QC_plot_QuantSeq_and_5PSeq.png"), 
        genomic_5PSeq_and_QuantSeq_combined_cumulative_QC, 
        width = fig_width_2column,
        height = 210,
        units = "mm",
        dpi = fig_dpi,
        bg = "white")


```

```{r plot-QC-cumulative-graph-plasmid-WT-vs-genome}

plasmid_vs_genome_polyA_QuantSeq <- full_length_QuantSeq_plasmids_cumulative_polyA_reads %>%
  filter(mod == "WT", !URA3) %>%
  bind_rows(full_length_QuantSeq_plasmids_cumulative_QC %>%
              filter(terminator %in% c("tRPS3", "tTSA1"),
                     sample %in% c("A12", "B12", "A1", "B1", "A5", "B5")))

plasmid_vs_genome_polyA_QuantSeq_TSA1_plot <- ggplot(plasmid_vs_genome_polyA_QuantSeq %>%
         filter(terminator == "tTSA1",
                sample %in% c("A5", "B5"))) +
  geom_step(aes(x = read_end,
                y = rel_cumulative_counts,
                colour = sample,
                linetype = mod)) +
  labs(x="", y="Fraction of Reads", title = "Genomic vs Plasmid TSA1 Poly(A) sites (QuantSeq)") +
  lims(x = c(80,120)) +
  guides(colour = "none", linetype = "none")

plasmid_vs_genome_polyA_QuantSeq_RPS3_plot <- ggplot(plasmid_vs_genome_polyA_QuantSeq %>%
         filter(terminator == "tRPS3",
                sample %in% c("A12", "B12", "A1", "B1"))) +
  geom_step(aes(x = read_end,
                y = rel_cumulative_counts,
                colour = sample,
                linetype = mod)) +
  labs(x="", y="Fraction of Reads", title = "Genomic vs Plasmid RPS3 Poly(A) sites (QuantSeq)") +
  lims(x = c(30,80)) +
  guides(colour = "none", linetype = "none")

plasmid_vs_genome_polyA_5PSeq <- full_length_5PSeq_plasmids_cumulative_polyA_reads %>%
  filter(mod == "WT", !URA3) %>%
  bind_rows(full_length_5PSeq_plasmids_cumulative_polyA_reads_genomic %>%
              filter(terminator %in% c("tRPS3", "tTSA1"),
                     sample %in% c("3dt", "4dt")))

plasmid_vs_genome_polyA_5PSeq_RPS3_plot <- ggplot(plasmid_vs_genome_polyA_5PSeq %>%
         filter(terminator == "tRPS3", !URA3)) +
  geom_step(aes(x = read_end,
                y = rel_cumulative_counts,
                colour = sample,
                linetype = mod)) +
  labs(x="", y="Fraction of Reads", title = "Genomic vs Plasmid RPS3 Poly(A) sites (5PSeq)") +
  lims(x = c(30,80)) +
  guides(colour = "none", linetype = "none")


plasmid_vs_genome_polyA_combined_plot <- plot_grid(plasmid_vs_genome_polyA_QuantSeq_TSA1_plot,
                                                   plasmid_vs_genome_polyA_QuantSeq_RPS3_plot,
                                                   plasmid_vs_genome_polyA_5PSeq_RPS3_plot,
                                                   get_legend(plasmid_vs_genome_polyA_5PSeq_RPS3_plot +
                       guides(linetype = guide_legend(nrow = 1)) +
                         scale_linetype_manual(name = "Location",
                                             values = c("genomic" = "solid", 
                                                        "WT" = "dotted"),
                                             labels = c("genomic" = "Genome", 
                                                        "WT" = "Plasmid")) +
                         theme(legend.justification = "centre",
                               legend.box.margin = margin(),
                               legend.box = "vertical",
                               legend.title = element_text(hjust = 0.5))),
                       ncol = 1,
                       rel_heights = c(1, 1, 1, 0.5))

```

```{r output-polyA-QC-plot, eval = FALSE}

ggsave2(here("supplementary_data_chapter/figures/plasmid_vs_genome_polyA_combined_plot.png"), 
        plasmid_vs_genome_polyA_combined_plot, 
        width = fig_width_2column,
        height = 210,
        units = "mm",
        dpi = fig_dpi,
        bg = "white")
```

```{r plot-cumulative-graph}
cumulative_graph_QuantSeq_pRPS3 <- ggplot(full_length_QuantSeq_plasmids_cumulative_polyA_reads %>%
  filter(promoter == "pRPS3", mod != "genomic", !URA3)) +
  geom_line(aes(x = read_end, y = rel_cumulative_counts, linetype = str_detect(sample, "A"), group = sample, colour = label)) +
  guides(linetype = FALSE, colour = FALSE) +
  labs(x="", y="Fraction of Reads", title = "pRPS3-tRPS3 (QuantSeq)") +
  scale_colour_manual(values = RPS3_TSA1_colour_scheme)

cumulative_graph_QuantSeq_pTSA1 <- ggplot(full_length_QuantSeq_plasmids_cumulative_polyA_reads %>%
  filter(promoter == "pTSA1", mod != "genomic", !URA3)) +
  geom_line(aes(x = read_end, y = rel_cumulative_counts, linetype = str_detect(sample, "A"), group = sample, colour = label)) +
  guides(colour = FALSE)  +
  labs(x="Position relative to stop codon", y="", title = "pTSA1-tTSA1 (QuantSeq)") +
  scale_linetype_discrete(labels = c(1,2), name = "Rep") +
  scale_colour_manual(values = RPS3_TSA1_colour_scheme)

cumulative_graph_QuantSeq_pPGK1 <- ggplot(full_length_QuantSeq_plasmids_cumulative_polyA_reads %>%
  filter(promoter == "pPGK1", mod != "genomic", !URA3)) +
  geom_line(aes(x = read_end, y = rel_cumulative_counts, linetype = str_detect(sample, "A"), group = sample, colour = label)) +
  guides(colour = FALSE, linetype = FALSE)  +
  labs(x="Position relative to stop codon", y="Fraction of Reads", title = "pPGK1-tRPS3 (QuantSeq)") +
  scale_colour_manual(values = RPS3_TSA1_colour_scheme)

cumulative_graph_QuantSeq_norm_genes <- ggplot(full_length_QuantSeq_genomic_cumulative_polyA_reads) +
  geom_line(aes(x = read_end, y = rel_cumulative_counts, linetype = sample, colour = promoter)) +
  guides(linetype = FALSE)  +
  labs(x="Position relative to stop codon", y="Fraction of Reads", title = "Normalising Genes (QuantSeq)")

cumulative_graph_5PSeq_pRPS3 <- ggplot(full_length_5PSeq_plasmids_cumulative_polyA_reads %>%
  filter(promoter == "pRPS3", mod != "genomic", !URA3)) +
  geom_line(aes(x = read_end, y = rel_cumulative_counts, linetype = str_detect(sample, "A"), group = sample, colour = label)) +
  guides(linetype = FALSE, colour = FALSE) +
  labs(x="", y="Fraction of Reads", title = "pRPS3-tRPS3 (5PSeq)") +
  scale_colour_manual(values = RPS3_TSA1_colour_scheme)

cumulative_graph_5PSeq_norm_genes <- ggplot(full_length_5PSeq_genomic_cumulative_polyA_reads) +
  geom_line(aes(x = read_end, y = rel_cumulative_counts, linetype = sample, colour = promoter)) +
  guides(linetype = FALSE)  +
  labs(x="Position relative to stop codon", y="Fraction of Reads", title = "Normalising Genes (5PSeq)")


```

```{r normalise-to-median-norm-gene}
transcript_counts_QuantSeq <- full_QuantSeq_PolyA_reads %>%
  group_by(promoter, terminator, mod, sample, URA3) %>%
  summarise(count = n())

median_norm_gene_counts_QuantSeq <- transcript_counts_QuantSeq %>%
  filter(mod == "genomic" | URA3) %>%
  group_by(sample) %>%
  summarise(norm_gene_count = median(count))

norm_transcript_counts_QuantSeq <- transcript_counts_QuantSeq %>%
  inner_join(median_norm_gene_counts_QuantSeq) %>%
  mutate(norm_count = count / norm_gene_count) %>%
  filter(!URA3, mod != "genomic") %>%
  select(-URA3)

mean_norm_modNNN_counts_QuantSeq <- norm_transcript_counts_QuantSeq %>%
  filter(mod == "mod0") %>%
  group_by(promoter) %>%
  summarise(mean_modNNN = mean(norm_count))

construct_fold_change_QuantSeq_mod_NNN <- norm_transcript_counts_QuantSeq %>%
  inner_join(mean_norm_modNNN_counts_QuantSeq) %>%
  mutate(rel_abund_delta_deltacq = norm_count / mean_modNNN) %>%
  inner_join(construct_to_label_dictionary_TSA1_RPS3, by = c("mod" = "construct")) %>%
  dplyr::rename("mod_label" = "label")

ggplot(construct_fold_change_QuantSeq_mod_NNN) +
  geom_point(aes(y = mod, x = rel_abund_delta_deltacq, colour = str_detect(sample, "A"))) +
  facet_wrap(~promoter) +
  guides(colour = FALSE) 

transcript_counts_5PSeq <- full_5PSeq_PolyA_reads %>%
  group_by(promoter, terminator, mod, sample, URA3) %>%
  summarise(count = n())

median_norm_gene_counts_5PSeq <- transcript_counts_5PSeq %>%
  filter(mod == "genomic" | URA3) %>%
  group_by(sample) %>%
  summarise(norm_gene_count = median(count))

norm_transcript_counts_5PSeq <- transcript_counts_5PSeq %>%
  inner_join(median_norm_gene_counts_5PSeq) %>%
  mutate(norm_count = count / norm_gene_count) %>%
  filter(!URA3, mod != "genomic") %>%
  select(-URA3)

mean_norm_modNNN_counts_5PSeq <- norm_transcript_counts_5PSeq %>%
  filter(mod == "mod0") %>%
  group_by(promoter) %>%
  summarise(mean_modNNN = mean(norm_count))

construct_fold_change_5PSeq_mod_NNN <- norm_transcript_counts_5PSeq %>%
  inner_join(mean_norm_modNNN_counts_5PSeq) %>%
  mutate(rel_abund_delta_deltacq = norm_count / mean_modNNN) %>%
  inner_join(construct_to_label_dictionary_TSA1_RPS3, by = c("mod" = "construct")) %>%
  dplyr::rename("mod_label" = "label")

ggplot(construct_fold_change_5PSeq_mod_NNN) +
  geom_point(aes(y = mod, x = rel_abund_delta_deltacq, colour = str_detect(sample, "A"))) +
  facet_wrap(~promoter) +
  guides(colour = FALSE)

```

```{r import_qPCR_results}
TSA1_deltadeltacq <- read_csv(here("raw_data_analysis/data/norm_qpcr/motif_context_dependence/pTSA1_pPGK1_pSRO9_tTSA1_deltadeltacq_platesnorm_summarise.csv")) %>%
  mutate(mod_label = factor(construct,
                       levels = construct_to_label_dictionary_TSA1_RPS3$construct,
                       labels = construct_to_label_dictionary_TSA1_RPS3$label),
         promoter = factor(promoter, levels = c("pTSA1","pPGK1","pSRO9")))

RPS3_deltadeltacq <- read_csv(here("raw_data_analysis/data/norm_qpcr/motif_context_dependence/pRPS3_pPGK1_pSRO9_tRPS3_deltadeltacq_platesnorm_summarise.csv")) %>%
  mutate(mod_label = factor(construct,
                       levels = construct_to_label_dictionary_TSA1_RPS3$construct,
                       labels = construct_to_label_dictionary_TSA1_RPS3$label),
         promoter = factor(promoter, levels = c("pRPS3","pPGK1","pSRO9")))

TSA1_deltadeltacq_plot <- ggplot(data = TSA1_deltadeltacq)+
  RNA_relative_abundance_figure_options +
  scale_colour_manual(values=RPS3_TSA1_colour_scheme) +
  theme(axis.text.y=element_text(colour=RPS3_TSA1_colour_scheme, face = "bold")) +
  labs(x ="Fold change in RNA abundance relative to tTSA1 mod_NNN", y = "") +
  facet_wrap(~promoter,ncol = 3) 

RPS3_deltadeltacq_plot <- ggplot(data = RPS3_deltadeltacq) +
  RNA_relative_abundance_figure_options +
  scale_colour_manual(values=RPS3_TSA1_colour_scheme) +
  theme(axis.text.y=element_text(colour=RPS3_TSA1_colour_scheme, face = "bold")) +
  labs(x ="Fold change in RNA abundance relative to tRPS3 mod_NNN", y = "") +
  facet_wrap(~promoter,ncol = 3) 

TSA1_deltadeltacq_plot

RPS3_deltadeltacq_plot

```

```{r compare_qPCR_and_RNAseq}
mean_qpcr_vs_QuantSeq_dataset_mod_NNN <- construct_fold_change_QuantSeq_mod_NNN %>%
              mutate(source = "RNA-Seq", type = "QuantSeq") %>%
  bind_rows(bind_rows(TSA1_deltadeltacq %>% filter(promoter == "pTSA1"),
                       RPS3_deltadeltacq%>% filter(promoter %in% c("pRPS3",
                                                                   "pPGK1"))) %>% 
              select(promoter, terminator, mod_label, rel_abund_delta_deltacq) %>%
              mutate(source = "qPCR", type = "QuantSeq") %>%
              filter(mod_label %in% c("mod_NNN","mod_NAA","WT", 
                                      "mod_HTH","mod_NTN"))) %>%
  group_by(promoter, source, mod_label, terminator, type) %>%
  summarise(mean_rel_abund = mean(rel_abund_delta_deltacq)) %>%
  ungroup() %>%
  pivot_wider(names_from = "source", values_from = "mean_rel_abund")

mean_qpcr_vs_5PSeq_dataset_mod_NNN <- construct_fold_change_5PSeq_mod_NNN %>%
              mutate(source = "RNA-Seq", type = "5PSeq") %>%
  bind_rows(bind_rows(RPS3_deltadeltacq%>% filter(promoter %in% c("pRPS3"))) %>% 
              select(promoter, terminator, mod_label, rel_abund_delta_deltacq) %>%
              mutate(source = "qPCR", type = "5PSeq") %>%
              filter(mod_label %in% c("mod_NNN","mod_NAA","WT", 
                                      "mod_HTH","mod_NTN","mod_HNH","mod_NGG"))) %>%
  group_by(promoter, source, mod_label, terminator, type) %>%
  summarise(mean_rel_abund = mean(rel_abund_delta_deltacq)) %>%
  ungroup() %>%
  pivot_wider(names_from = "source", values_from = "mean_rel_abund")

qPCR_vs_RNASeq_plot_QuantSeq <- ggplot(mean_qpcr_vs_QuantSeq_dataset_mod_NNN ) +
  geom_point(aes(x = `RNA-Seq`, y = qPCR, colour = mod_label)) +
  geom_abline(slope = 1, intercept = 0) +
  coord_equal() +
  facet_wrap(~promoter, nrow = 1) +
  scale_colour_manual(values = RPS3_TSA1_colour_scheme) +
  guides(colour = "none")

qPCR_vs_RNASeq_plot_5PSeq <- ggplot(mean_qpcr_vs_5PSeq_dataset_mod_NNN ) +
  geom_point(aes(x = `RNA-Seq`, y = qPCR, colour = mod_label, shape = terminator)) +
  geom_abline(slope = 1, intercept = 0) +
  guides(colour = "none", shape = "none") +
  scale_colour_manual(values = RPS3_TSA1_colour_scheme) +
  theme(legend.box = "horizontal") +
  coord_equal()

mean_qpcr_vs_QuantSeq_dataset_mod_NNN_R_squared <- mean_qpcr_vs_QuantSeq_dataset_mod_NNN %>%
  group_by(promoter) %>%
  summarise(R_squared = cor(qPCR, `RNA-Seq`)^2)

mean_qpcr_vs_5PSeq_dataset_mod_NNN_R_squared <- mean_qpcr_vs_5PSeq_dataset_mod_NNN %>%
  summarise(R_squared = cor(qPCR, `RNA-Seq`)^2)

```


```{r plot-functions}
cumulative_reads_plot <- list(geom_step(aes(x = read_end_gap,
                                            y = rel_cumulative_counts,
                                            linetype = promoter,
                                            colour = label,
                                            group = sample)),
                              labs(x="",
                                   y="Cumulative \n Fraction of Reads",
                                   linetype = "Promoter",
                                   shape = "Promoter",
                                   colour = "Construct"),
                              guides(linetype = "none",
                                     shape = "none",
                                     colour = "none"),
                              theme(legend.position = "bottom",
                                    panel.border = element_blank()),
                              scale_y_continuous(expand = expansion(add = c(0.001,0.05)),
                                                 labels = c("0", "", "0.5", "", "1")),
                              scale_colour_manual(values = RPS3_TSA1_colour_scheme),
                              scale_shape_discrete(drop = FALSE),
                              scale_linetype_manual(values = c("pRPS3" = "solid", "pPGK1" = "dashed", "pTSA1" = "dotdash")))

polyA_site_usage_plot <- list(geom_point(aes(y = factor(read_end), 
                                             x = rel_cumulative_counts, 
                                             colour = label)),
                              labs(y="", 
                                   x="Cumulative Fraction \n of Reads"),
                              theme(legend.position = "bottom",
                                    panel.margin = unit(0, "lines"),
                                    strip.placement = "outside",
                                    strip.text.y.left = element_markdown(face = "bold", 
                                                                         size = 12, 
                                                                         angle = 0)),                           
                              scale_colour_manual(values = RPS3_TSA1_colour_scheme),
                              guides(colour = "none", shape = "none"))

construct_sequence_plots <- list(theme(axis.ticks = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.border = element_blank(),
        axis.line.y = element_blank()),
  labs(x="Position relative to stop codon"))

```

```{r create-motifs-gaps-in-wt}
tRPS3_motif_insertion_sites <- tibble(site = c(1,2,3), start = c(24, 48, 61), end = c(32, 56, 69))

tTSA1_motif_insertion_sites <- tibble(site = c(1,2,3), start = c(21, 50, 83), end = c(29, 58, 91))


tRPS3_WT_insertion_alpha <- full_length_QuantSeq_plasmids_cumulative_polyA_reads %>%
  mutate(read_end_gap = ifelse(mod != "WT" | terminator != "tRPS3", read_end,
                         ifelse(read_end >= tRPS3_motif_insertion_sites$start[3] - 18, read_end + 27,
                         ifelse(read_end >= tRPS3_motif_insertion_sites$start[2] - 9, read_end + 18,
                         ifelse(read_end >= tRPS3_motif_insertion_sites$start[1], read_end + 9, read_end)))))

tRPS3_WT_insertion_alpha_5PSeq <- full_length_5PSeq_plasmids_cumulative_polyA_reads %>%
  mutate(read_end_gap = ifelse(mod != "WT" | terminator != "tRPS3", read_end,
                         ifelse(read_end >= tRPS3_motif_insertion_sites$start[3] - 18, read_end + 27,
                         ifelse(read_end >= tRPS3_motif_insertion_sites$start[2] - 9, read_end + 18,
                         ifelse(read_end >= tRPS3_motif_insertion_sites$start[1], read_end + 9, read_end)))))

tRPS3_missing_values <- tRPS3_WT_insertion_alpha %>%
  filter(mod == "WT",
         terminator == "tRPS3", 
         !URA3,
         (read_end <= tRPS3_motif_insertion_sites$end[1] & 
           read_end >= tRPS3_motif_insertion_sites$start[1]) |
         (read_end <= tRPS3_motif_insertion_sites$end[2] &
           read_end >= tRPS3_motif_insertion_sites$start[2]) |
         (read_end <= tRPS3_motif_insertion_sites$end[3] &
           read_end >= tRPS3_motif_insertion_sites$start[3])) %>%
  mutate(rel_cumulative_counts = NA,
         read_end_gap = read_end)

tRPS3_missing_values_5PSeq <- tRPS3_WT_insertion_alpha_5PSeq %>%
  filter(mod == "WT",
         terminator == "tRPS3", 
         !URA3,
         (read_end <= tRPS3_motif_insertion_sites$end[1] & 
           read_end >= tRPS3_motif_insertion_sites$start[1]) |
         (read_end <= tRPS3_motif_insertion_sites$end[2] &
           read_end >= tRPS3_motif_insertion_sites$start[2]) |
         (read_end <= tRPS3_motif_insertion_sites$end[3] &
           read_end >= tRPS3_motif_insertion_sites$start[3])) %>%
  mutate(rel_cumulative_counts = NA,
         read_end_gap = read_end)



tRPS3_WT_insertion_gaps <- full_length_QuantSeq_plasmids_cumulative_polyA_reads %>%
  filter(mod == "WT",
         terminator == "tRPS3",
         !URA3,
         read_end >= tRPS3_motif_insertion_sites$start[1] - 1,
         read_end <= tRPS3_motif_insertion_sites$end[3]) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tRPS3_motif_insertion_sites$end[3],
                rel_cumulative_counts[read_end == tRPS3_motif_insertion_sites$start[3] - 19],
                rel_cumulative_counts)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tRPS3_motif_insertion_sites$start[3] - 1,
                NA,
                rel_cumulative_counts_gap)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tRPS3_motif_insertion_sites$end[2],
                rel_cumulative_counts[ read_end == tRPS3_motif_insertion_sites$start[2] - 10],
                rel_cumulative_counts_gap)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tRPS3_motif_insertion_sites$start[2] - 1,
                NA,
                rel_cumulative_counts_gap)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tRPS3_motif_insertion_sites$end[1],
                rel_cumulative_counts[read_end == tRPS3_motif_insertion_sites$start[1] - 1],
                rel_cumulative_counts_gap))

tRPS3_WT_insertion_gaps_5PSeq <- full_length_5PSeq_plasmids_cumulative_polyA_reads %>%
  filter(mod == "WT",
         terminator == "tRPS3",
         !URA3,
         read_end >= tRPS3_motif_insertion_sites$start[1] - 1,
         read_end <= tRPS3_motif_insertion_sites$end[3]) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tRPS3_motif_insertion_sites$end[3],
                rel_cumulative_counts[read_end == tRPS3_motif_insertion_sites$start[3] - 19],
                rel_cumulative_counts)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tRPS3_motif_insertion_sites$start[3] - 1,
                NA,
                rel_cumulative_counts_gap)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tRPS3_motif_insertion_sites$end[2],
                rel_cumulative_counts[ read_end == tRPS3_motif_insertion_sites$start[2] - 10],
                rel_cumulative_counts_gap)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tRPS3_motif_insertion_sites$start[2] - 1,
                NA,
                rel_cumulative_counts_gap)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tRPS3_motif_insertion_sites$end[1],
                rel_cumulative_counts[read_end == tRPS3_motif_insertion_sites$start[1] - 1],
                rel_cumulative_counts_gap))

tTSA1_WT_insertion_alpha <- full_length_QuantSeq_plasmids_cumulative_polyA_reads %>%
  mutate(read_end_gap = ifelse(mod != "WT" | terminator != "tTSA1", read_end,
                         ifelse(read_end >= tTSA1_motif_insertion_sites$start[3] - 18, read_end + 27,
                         ifelse(read_end >= tTSA1_motif_insertion_sites$start[2] - 9, read_end + 18,
                         ifelse(read_end >= tTSA1_motif_insertion_sites$start[1], read_end + 9, read_end)))))

tTSA1_missing_values <- tTSA1_WT_insertion_alpha %>%
  filter(mod == "WT",
         terminator == "tTSA1", 
         !URA3,
         (read_end <= tTSA1_motif_insertion_sites$end[1] & 
           read_end >= tTSA1_motif_insertion_sites$start[1]) |
         (read_end <= tTSA1_motif_insertion_sites$end[2] &
           read_end >= tTSA1_motif_insertion_sites$start[2]) |
         (read_end <= tTSA1_motif_insertion_sites$end[3] &
           read_end >= tTSA1_motif_insertion_sites$start[3])) %>%
  mutate(rel_cumulative_counts = NA,
         read_end_gap = read_end)

tTSA1_WT_insertion_gaps <- full_length_QuantSeq_plasmids_cumulative_polyA_reads %>%
  filter(mod == "WT",
         terminator == "tTSA1",
         !URA3,
         read_end >= tTSA1_motif_insertion_sites$start[1] - 1,
         read_end <= tTSA1_motif_insertion_sites$end[3]) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tTSA1_motif_insertion_sites$end[3],
                rel_cumulative_counts[read_end == tTSA1_motif_insertion_sites$start[3] - 19],
                rel_cumulative_counts)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tTSA1_motif_insertion_sites$start[3] - 1,
                NA,
                rel_cumulative_counts_gap)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tTSA1_motif_insertion_sites$end[2],
                rel_cumulative_counts[ read_end == tTSA1_motif_insertion_sites$start[2] - 10],
                rel_cumulative_counts_gap)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tTSA1_motif_insertion_sites$start[2] - 1,
                NA,
                rel_cumulative_counts_gap)) %>%
  mutate(rel_cumulative_counts_gap = ifelse(read_end <= tTSA1_motif_insertion_sites$end[1],
                rel_cumulative_counts[read_end == tTSA1_motif_insertion_sites$start[1] - 1],
                rel_cumulative_counts_gap)) 

```

```{r create-figure-QuantSeq}
RPS3_terminator_sequence = tibble(position = 1:227, 
                                  mod_NNN = str_split("ATTTAATTATTAAATACATAAATCGTCTACGAAAACTATAAGTACAAACTACGCCTTAATGCTTGAGGATTCTTCTATTCTAGTGCACTTAATTGTTGCGGTTTCTTGCATATTGCCGTGTTTAGTCAGGAGGGTGCACGTTGAAGCAGTGCGTTGAAACTAGTTGTTATTTACAGAATCACAATATTATATAATCAAAAGAAAAGTTTTGTACAACACAACTGTGA","")[[1]]) %>%
  pivot_longer(- position, names_to = "construct", values_to = "nucleotide") %>%
  mutate(colour = ifelse(construct == "WT","black",
                         ifelse(position <= tRPS3_motif_insertion_sites$end[1] &
                                position >= tRPS3_motif_insertion_sites$start[1], "white",
                         ifelse(position <= tRPS3_motif_insertion_sites$end[2] &
                                position >= tRPS3_motif_insertion_sites$start[2], "white",
                         ifelse(position <= tRPS3_motif_insertion_sites$end[3] &
                                position >= tRPS3_motif_insertion_sites$start[3], "white", "black")))))

TSA1_terminator_sequence = tibble(position = 1:246, 
                                  mod_NNN = str_split("GACGCTTGCAGAGTTGTCTAAAATCACAGAATGACTACTTATTTAAAATCAAGTTAATTCACTCTTTACGTTTATACCTATCTTATGTTGGTATCTATATATAAAACCCATAAACTTAATGCTATTCACTGACAAAACGATACACTACCGTCTAAGAAGCTATTCACACTAGCTCAGTTCTAATAACAATCATCGTCTGGCTCTAAAACGCGTAAACCATTCACTGCCACACTCACTTTAGCTCTG","")[[1]]) %>%
  pivot_longer(- position, names_to = "construct", values_to = "nucleotide") %>%
  mutate(colour = ifelse(construct == "WT","black",
                         ifelse(position <= tTSA1_motif_insertion_sites$end[1] &
                                position >= tTSA1_motif_insertion_sites$start[1], "white",
                         ifelse(position <= tTSA1_motif_insertion_sites$end[2] &
                                position >= tTSA1_motif_insertion_sites$start[2], "white",
                         ifelse(position <= tTSA1_motif_insertion_sites$end[3] &
                                position >= tTSA1_motif_insertion_sites$start[3], "white", "black")))))

pPGK1_pRPS3_cumulative_plot <- ggplot(tRPS3_WT_insertion_alpha %>%
                                        bind_rows(tRPS3_missing_values) %>%
                                        mutate(source = "QuantSeq") %>%
         filter(promoter %in% c("pRPS3", "pPGK1"), 
                mod %in% c("WT", "mod0"), 
                !URA3)) +
  geom_line(data = tRPS3_WT_insertion_gaps,
             aes(x = read_end,
                 y = rel_cumulative_counts_gap,
                 group = sample),
             colour = "red") +
  geom_vline(xintercept = c(58, 77), 
             size = 0.3) +
  labs(title = "tRPS3 PolyA Sites") +
  cumulative_reads_plot +
  scale_x_continuous(limits = c(47, 91),
                     expand = expansion(add = c(1,1))) +
  theme(plot.margin = margin(l = 20),
        axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())

pPGK1_pRPS3_construct_sequence <- ggplot() + 
  geom_blank(data = RPS3_terminator_sequence,
             aes(x = position, y = construct)) +
  geom_rect(data = tRPS3_motif_insertion_sites,
            aes(xmin = start - 0.5, xmax = end + 0.5,
                ymin = 0.75, ymax = 1.25)) + 
  geom_text(data = RPS3_terminator_sequence,
            aes(label = nucleotide, x = position, y = construct),
            colour = RPS3_terminator_sequence$colour,
            size = 2,
            family = "Mono") +
  scale_x_continuous(limits = c(47, 91),
                     expand = expansion(add = c(1,1))) +
  construct_sequence_plots +
  theme(plot.margin = margin(l = 20))

pPGK1_pRPS3_cumulative_plot_with_seq <- plot_grid(pPGK1_pRPS3_cumulative_plot,
          pPGK1_pRPS3_construct_sequence,
          nrow = 2,
          align = "v",
          axis = "l",
          rel_heights = c(2,1))

pPGK1_pRPS3_cumulative_plot_all_constructs <- ggplot(tRPS3_WT_insertion_alpha %>%
                                        bind_rows(tRPS3_missing_values)  %>% 
                                        mutate(source = "QuantSeq") %>%
         filter(promoter %in% c("pRPS3", "pPGK1"), 
                mod != "WT", 
                !URA3))  +
  geom_vline(xintercept = c(58, 77), 
             size = 0.3) +
  geom_point(data = tRPS3_WT_insertion_alpha %>%
               filter(promoter %in% c("pRPS3", "pPGK1"),
                      mod != "WT",
                      !URA3,
                      read_end_gap %in% c(58, 77)),
             aes(x = read_end_gap,
                 y = rel_cumulative_counts,
                 colour = label))  +
  cumulative_reads_plot +
  labs(title = "tRPS3 Poly(A) Sites",
       x="Position relative to stop codon") +
  scale_x_continuous(limits = c(47, 91),
                     expand = expansion(add = c(1,1))) +
  facet_grid(promoter~label) +
  scale_colour_manual(values = RPS3_TSA1_colour_scheme[c("WT", "mod_HTH", "mod_NTN", "mod_NAA", "mod_NNN")]) +
   theme(panel.spacing.y = unit(0.4, "cm", data = NULL))

pTSA1_cumulative_plot <- ggplot(tTSA1_WT_insertion_alpha %>%
                                        bind_rows(tTSA1_missing_values) %>% 
                                        mutate(source = "QuantSeq") %>%
         filter(promoter == "pTSA1", 
                mod %in% c("WT", "mod0"), 
                !URA3)) +
  geom_line(data = tTSA1_WT_insertion_gaps,
             aes(x = read_end,
                 y = rel_cumulative_counts_gap,
                 group = sample),
             colour = "red") +
  geom_vline(xintercept = c(127, 133), 
             size = 0.3)  +
  scale_x_continuous(limits = c(110, 150),
                     expand = expansion(add = c(1,1))) +
  cumulative_reads_plot +
  guides(colour = "none") +
  labs(y="", 
       x = "",
       title = "tTSA1 Poly(A) Sites") +
  theme(plot.margin = margin(r = 20),
        axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())



pTSA1_construct_sequence <- ggplot() + 
  geom_blank(data = TSA1_terminator_sequence,
             aes(x = position, y = construct)) +
  geom_rect(data = tTSA1_motif_insertion_sites,
            aes(xmin = start - 0.5, xmax = end + 0.5,
                ymin = 0.75, ymax = 1.25)) + 
  geom_text(data = TSA1_terminator_sequence,
            aes(label = nucleotide, x = position, y = construct),
            colour = TSA1_terminator_sequence$colour,
            size = 2,
            family = "Mono") +
  scale_x_continuous(limits = c(110, 150),
                     expand = expansion(add = c(1,1))) +
  construct_sequence_plots +
  theme(axis.text.y = element_blank(),
        plot.margin = margin(r = 20))

pTSA1_cumulative_plot_with_seq <- plot_grid(pTSA1_cumulative_plot,
          pTSA1_construct_sequence,
          nrow = 2,
          align = "v",
          axis = "l",
          rel_heights = c(2,1))

pTSA1_cumulative_plot_all_constructs <- ggplot(tTSA1_WT_insertion_alpha %>%
                                        bind_rows(tTSA1_missing_values) %>%
                                        mutate(source = "QuantSeq") %>%
         filter(promoter == "pTSA1",
                      mod != "WT", 
                !URA3)) +
  geom_vline(xintercept = c(127, 133), 
             size = 0.3) +
  geom_point(data = tTSA1_WT_insertion_alpha %>%
               filter(promoter == "pTSA1",
                      mod != "WT",
                      !URA3,
                      read_end_gap %in% c(127, 133)),
             aes(x = read_end_gap,
                 y = rel_cumulative_counts,
                 colour = label))  +
  scale_x_continuous(limits = c(110, 145),
                     expand = expansion(add = c(1,1)),
                     breaks = c(110,120,130,140)) +
  cumulative_reads_plot +
  guides(colour = "none") +
  labs(x = "Position relative to stop codon",
       title = "tTSA1 Poly(A) Sites") +
  facet_grid(promoter~label)

quantseq_polya_site_usage_plot <- plot_grid(qPCR_vs_RNASeq_plot_QuantSeq,
          plot_grid(pPGK1_pRPS3_cumulative_plot_with_seq,
                             pTSA1_cumulative_plot_with_seq),
          plot_grid(pPGK1_pRPS3_cumulative_plot_all_constructs,
                             pTSA1_cumulative_plot_all_constructs,
                    get_legend(pPGK1_pRPS3_cumulative_plot_all_constructs +
                                guides(colour = guide_legend(ncol=2),
                                       linetype = guide_legend(ncol=1)) +
                                theme(legend.justification = "centre",
                                      legend.box.margin = margin())),
                             ncol = 1,
                             rel_heights = c(2,1.50,0.8)),
          ncol = 1,
          labels = "AUTO",
          rel_heights = c(1,1.1,2.5))
```

```{r relative-counts-plots}
relative_polya_counts_pRPS3_5PSeq <- ggplot(full_5PSeq_cumulative_polyA_reads %>%
         filter(!mod %in% c("genomic", "WT"),
                !URA3) %>%
  inner_join(construct_to_label_dictionary_TSA1_RPS3, by = c("mod" = "construct"))) +
  geom_step(aes(x = read_end,
                y = rel_counts,
                group = sample,
                colour = label),
            alpha = 0.7) +
  facet_grid(promoter~label) +
  labs(title = "Relative Poly(A) Counts (5PSeq)",
       x="Position relative to stop codon",
      y="Fraction of Reads",
      linetype = "Promoter",
      colour = "Construct") +
  guides(linetype = "none") +
  scale_colour_manual(values = RPS3_TSA1_colour_scheme)+
  lims(x = c(47, 91)) +
  theme(legend.position = "bottom")

QuantSeq_relative_polya_counts_pPGK1_pRPS3<- ggplot(full_QuantSeq_cumulative_polyA_reads %>%
         filter(!mod %in% c("genomic", "WT"),
                !URA3,
                terminator != "tTSA1") %>%
  inner_join(construct_to_label_dictionary_TSA1_RPS3, by = c("mod" = "construct"))) +
  geom_step(aes(x = read_end,
                y = rel_counts,
                group = sample,
                colour = label),
            alpha = 0.7) +
  facet_grid(promoter~label) +
  lims(x = c(47, 91)) +
  labs(title = "Relative Poly(A) Counts (QuantSeq)",
       x="Position relative to stop codon",
      y="Fraction of Reads",
      linetype = "Promoter",
      colour = "Construct") +
  guides(linetype = "none",
         colour = "none") +
  scale_colour_manual(values = RPS3_TSA1_colour_scheme)

QuantSeq_relative_polya_counts_pTSA1<- ggplot(full_QuantSeq_cumulative_polyA_reads %>%
         filter(!mod %in% c("genomic", "WT"),
                !URA3,
                terminator == "tTSA1") %>%
  inner_join(construct_to_label_dictionary_TSA1_RPS3, by = c("mod" = "construct"))) +
  geom_step(aes(x = read_end,
                y = rel_counts,
                group = sample,
                colour = label),
            alpha = 0.7) +
  facet_grid(promoter~label) +
  labs(x="Position relative to stop codon",
      y="Fraction of Reads",
      linetype = "Promoter",
      colour = "Construct") +
  guides(linetype = "none",
         colour = "none") +
  scale_colour_manual(values = RPS3_TSA1_colour_scheme) +
  scale_x_continuous(breaks = c(100, 120, 140),
                     limits = c(90, 145))

relative_polya_counts_QuantSeq_and_5PSeq <- plot_grid(QuantSeq_relative_polya_counts_pPGK1_pRPS3,
          QuantSeq_relative_polya_counts_pTSA1,
          relative_polya_counts_pRPS3_5PSeq,
          ncol = 1,
          rel_heights = c(1, 0.5, 0.7))
```

```{r print-out-quantseq-results}
ggsave2(here("./results_chapter/figures/polya_usage_plot_QuantSeq.png"), 
        quantseq_polya_site_usage_plot, 
        width = fig_width_2column,
        height = 210,
        units = "mm",
        dpi = fig_dpi,
        bg = "white")

ggsave2(here("./supplementary_data_chapter/figures/relative_polya_counts_QuantSeq_and_5PSeq.png"), 
        relative_polya_counts_QuantSeq_and_5PSeq, 
        width = fig_width_2column,
        height = 210,
        units = "mm",
        dpi = fig_dpi,
        bg = "white")
```

```{r create-figure-5PSeq}
tRPS3_WT_insertion_alpha_5PSeq_and_QuantSeq <- tRPS3_WT_insertion_alpha_5PSeq %>%
  bind_rows(tRPS3_missing_values_5PSeq) %>%
  mutate(source = "5PSeq") %>%
  bind_rows(tRPS3_WT_insertion_alpha %>% 
              bind_rows(tRPS3_missing_values) %>%
              filter(promoter == "pRPS3") %>%
              mutate(source = "QuantSeq"))

tRPS3_cumulative_plot_5PSeq <- ggplot(tRPS3_WT_insertion_alpha_5PSeq_and_QuantSeq %>%
         filter(promoter %in% c("pRPS3", "pPGK1"), 
                source == "5PSeq",
                mod %in% c("WT", "mod0"), 
                !URA3)) +
  geom_step(data = tRPS3_WT_insertion_gaps_5PSeq,
             aes(x = read_end,
                 y = rel_cumulative_counts_gap,
                 group = sample),
             colour = "red") +
  geom_vline(xintercept = c(58, 77), 
             size = 0.3) +
  labs(title = "tRPS3 Poly(A) Sites") +
  cumulative_reads_plot +
  scale_x_continuous(limits = c(47, 91),
                     expand = expansion(add = c(1,1))) +
  theme(plot.margin = margin(l = 20),
        axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())

tRPS3_cumulative_plot_with_seq_5PSeq <- plot_grid(tRPS3_cumulative_plot_5PSeq,
          pPGK1_pRPS3_construct_sequence,
          nrow = 2,
          align = "v",
          axis = "l",
          rel_heights = c(2,1))

tRPS3_cumulative_plot_all_constructs_5PSeq <- ggplot(tRPS3_WT_insertion_alpha_5PSeq_and_QuantSeq %>%
         filter(promoter %in% c("pRPS3", "pPGK1"), 
                mod != "WT", 
                source == "5PSeq",
                !URA3)) +
  geom_vline(xintercept = c(58, 77), 
             size = 0.3) +
  geom_point(data = tRPS3_WT_insertion_alpha_5PSeq %>%
               filter(promoter %in% c("pRPS3", "pPGK1"),
                      mod != "WT",
                      !URA3,
                      read_end_gap %in% c(58, 77)),
             aes(x = read_end_gap,
                 shape = promoter,
                 y = rel_cumulative_counts,
                 colour = label))  +
  cumulative_reads_plot +
  labs(title = "tRPS3 Poly(A) Sites",
       x="Position relative to stop codon",
       linetype = "RNA-Seq") +
  scale_x_continuous(limits = c(47, 91),
                     expand = expansion(add = c(1,1))) +
  facet_wrap(~label, nrow = 2)


polya_site_usage_plot_5PSeq <- plot_grid(plot_grid(qPCR_vs_RNASeq_plot_5PSeq,
          tRPS3_cumulative_plot_with_seq_5PSeq, 
          nrow = 1,
          labels = c("", "B"),
          rel_widths = c(0.8,1.5)),
          plot_grid(tRPS3_cumulative_plot_all_constructs_5PSeq,
                    get_legend(tRPS3_cumulative_plot_all_constructs_5PSeq +
                                guides(colour = guide_legend(nrow=2)) +
                                theme(legend.justification = "centre",
                                      legend.box.margin = margin(),
                                      legend.box = "vertical")),
                             ncol = 1,
                             rel_heights = c(2,1)),
          ncol = 1,
          labels = c("A", "C"),
          rel_heights = c(1,2))
```

```{r print-out-5pseq-results}

ggsave2(here("supplementary_data_chapter/figures/polya_usage_plot_5PSeq.png"), 
        polya_site_usage_plot_5PSeq, 
        width = fig_width_2column,
        height = 150,
        units = "mm",
        dpi = fig_dpi,
        bg = "white")
```
