---
title: "Compare platereader vs qpcr results"
output: html_document
---


```{r}
library(tidyverse)
library(here)

RPS3_protein <- read.csv(here("raw_data_analysis/data/platereader/pRPS3-mCh-tRPS3/refurbished_platereader_20200912-tRPS3mod200/refurb_fluorescence_per_od_200bp_pRPS3_tRPS3_n2.csv")) %>%
  filter(strain != "null") %>%
  separate(strain,into = c("strain","biorep"),sep = "_clone_") %>%
  mutate(exp = "1") %>% 
  bind_rows(
    read.csv(here("raw_data_analysis/data/platereader/pRPS3-mCh-tRPS3/refurbished_platereader_20200924-tRPS3mod200/refurb_fluorescence_per_od_200bp_pRPS3_tRPS3_n4.csv")) %>%
      filter(strain != "null") %>%
      separate(strain,into = c("strain","biorep"),sep = "_clone_") %>%
      mutate(exp = "2"))

TSA1_protein <- read.csv(here("raw_data_analysis/data/platereader/pTSA1-mCh-tTSA1/20201028_pTSA1_tTSA1_n1/fluorescence_per_od_exp_rep_1_fixed_old_platereader.csv")) %>%
  filter(strain != "null") %>%
  separate(strain,into = c("strain","biorep"),sep = " clone ") %>%
  mutate(exp = "1") %>% 
  bind_rows(
    read.csv(here("raw_data_analysis/data/platereader/pTSA1-mCh-tTSA1/20201104_pTSA1_tTSA1_n2/fluorescence_per_od_exp_rep_2_fixed_old_platereader.csv")) %>%
      filter(strain != "null") %>%
      separate(strain,into = c("strain","biorep"),sep = " clone ") %>%
      mutate(exp = "2"))

RPS3_RNA <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pRPS3_tRPS3_n1_n2_norm_mean.csv")) %>%
  group_by(construct, bio_rep) %>%
  summarise(delta_cq = median(delta_cq), .groups = "drop") %>%
  mutate(mod0_delta_cq = filter(., construct == "mod0") %>% pull(delta_cq) %>% mean()) %>%
  group_by(construct) %>%
  mutate( delta_delta_cq = delta_cq - mod0_delta_cq) %>%
  ungroup()

TSA1_RNA <- read_csv(here("./raw_data_analysis/data/norm_qpcr/pTSA1_tTSA1_n1_n2_norm_mean.csv")) %>%
  group_by(construct, bio_rep) %>%
  summarise(delta_cq = median(delta_cq, na.rm = TRUE), .groups = "drop") %>%
  mutate(mod0_delta_cq = filter(., construct == "mod0") %>% pull(delta_cq) %>% mean()) %>%
  group_by(construct) %>%
  mutate( delta_delta_cq = delta_cq - mod0_delta_cq) %>%
  ungroup()

strain_name_dictionary <- tibble(TSA1_RNA = TSA1_RNA %>% distinct(construct) %>% pull(construct), RPS3_RNA = RPS3_RNA %>% distinct(construct) %>% pull(construct), RPS3_protein = RPS3_protein %>% filter(strain != "POT1-ccdB") %>% distinct(strain) %>% pull(strain), TSA1_protein = c("tTSA1-200bp-mod0", "tTSA1-200bp-modA", "tTSA1-200bp-modB", "tTSA1-200bp-modC", "tTSA1-200bp-modD", "tTSA1-200bp-modE", "tTSA1-WT-200bp"))
```

```{r plotGraphs}
RPS3_protein_graph <- ggplot(RPS3_protein %>% inner_join(strain_name_dictionary, by = c("strain" = "RPS3_protein"))) +
  geom_point(aes(y=factor(RPS3_RNA, c("modC", "modE", "modD", "modA", "modB", "mod0", "WT")), x = mCherry.100.per.OD.at.max.local.gr, colour = RPS3_RNA), size = 3, show.legend = FALSE, alpha = 0.5)  +
  geom_errorbarh(aes(xmin = mCherry.100.per.OD.at.max.local.gr, xmax = mCherry.100.per.OD.at.max.local.gr, y = factor(RPS3_RNA, c("modC", "modE", "modD", "modA", "modB", "mod0", "WT")), colour = RPS3_RNA), RPS3_protein %>% inner_join(strain_name_dictionary, by = c("strain" = "RPS3_protein")) %>% group_by(RPS3_RNA) %>% summarise(mCherry.100.per.OD.at.max.local.gr = mean(mCherry.100.per.OD.at.max.local.gr)), show.legend = FALSE, size = 1) +
  theme_bw(base_size = 20) +
  labs(y = NULL, x = NULL) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.margin = margin(20,5,5,5)) +
  coord_cartesian(xlim = c(1800,8100))
 
RPS3_RNA_graph <- ggplot(RPS3_RNA) +
  geom_point(aes(y=factor(construct, c("modC", "modE", "modD", "modA", "modB", "mod0", "WT")), x = 2^-delta_cq, colour = construct), size = 3, show.legend = FALSE, alpha = 0.5) +
  theme_bw(base_size = 20) +
  geom_errorbarh(aes(xmin = delta_cq, xmax = delta_cq, y = factor(construct, c("modC", "modE", "modD", "modA", "modB", "mod0", "WT")), colour = construct), RPS3_RNA %>% group_by(construct) %>% summarise(delta_cq = mean(2^-delta_cq)), show.legend = FALSE, size = 1) +
  labs(y = NULL, x = NULL) +
  theme(panel.grid.minor.x = element_blank(), plot.margin = margin(20,5,5,5))

TSA1_protein_graph <- ggplot(TSA1_protein %>% inner_join(strain_name_dictionary, by = c("strain" = "TSA1_protein"))) +
  geom_point(aes(y=factor(TSA1_RNA, c("modC", "modE", "modD", "modA", "modB", "mod0", "WT")), x = mCherry.100.per.OD.at.max.local.gr, colour = TSA1_RNA), size = 3, show.legend = FALSE, alpha = 0.5) +
  geom_errorbarh(aes(xmin = mCherry.100.per.OD.at.max.local.gr, xmax = mCherry.100.per.OD.at.max.local.gr, y = factor(TSA1_RNA, c("modC", "modE", "modD", "modA", "modB", "mod0", "WT")), colour = TSA1_RNA), TSA1_protein %>% inner_join(strain_name_dictionary, by = c("strain" = "TSA1_protein")) %>% group_by(TSA1_RNA) %>% summarise(mCherry.100.per.OD.at.max.local.gr = mean(mCherry.100.per.OD.at.max.local.gr)), show.legend = FALSE, size = 1) +
  theme_bw(base_size = 20) +
  labs(y = NULL, x = "Fluorescence per OD at max growth rate") +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.margin = margin(20,5,5,5))

TSA1_RNA_graph <- ggplot(TSA1_RNA) +
  geom_point(aes(y=factor(construct, c("modC", "modE", "modD", "modA", "modB", "mod0", "WT")), x = 2^-delta_cq, colour = construct), size = 3, show.legend = FALSE, alpha = 0.5) +
  geom_errorbarh(aes(xmin = delta_cq, xmax = delta_cq, y = factor(construct, c("modC", "modE", "modD", "modA", "modB", "mod0", "WT")), colour = construct), TSA1_RNA %>% group_by(construct) %>% summarise(delta_cq = mean(2^-delta_cq)), show.legend = FALSE, size = 1) + 
  theme_bw(base_size = 20) +
  labs(y = NULL, x = "Fold change in RNA abundance") +
  theme(panel.grid.minor.x = element_blank(), plot.margin = margin(20,5,5,5))

RPS3_protein_graph_alone <- ggplot(RPS3_protein %>% inner_join(strain_name_dictionary, by = c("strain" = "RPS3_protein"))) +
  geom_point(aes(y=factor(TSA1_RNA, c("modC", "modE", "modD", "modA", "modB", "mod0", "WT")), x = mCherry.100.per.OD.at.max.local.gr, shape = exp, colour = strain), size = 3, show.legend = FALSE) +
  theme_bw(base_size = 20) +
  labs(y = NULL, x = "Fluorescence per OD at max growth rate", title = "RPS3 mCherry Fluorescence")

combined_TSA1_RPSA_protein_RNA_plots <- cowplot::plot_grid(cowplot::plot_grid(RPS3_RNA_graph, RPS3_protein_graph),cowplot::plot_grid(TSA1_RNA_graph, TSA1_protein_graph), labels = c("RPS3", "TSA1"), ncol = 1)

ggsave(filename = here("./results_chapter/figures/combined_TSA1_RPSA_protein_RNA_plot.png"), combined_TSA1_RPSA_protein_RNA_plots, width = 12, height = 10)
```
