---
title: "Comparison of protein vs mRNA levels of motifs inserted in RPS3, TSA1 and PIR1 motifs"
output: html_document
---

The goal of this is to make a plot comparing protein abundance with mRNA abundance, for constructs with different motif insertions in 3'UTRs, expressed from different promoters.


```{r setup}
library(here)
library(dplyr)
library(tibble)
library(stringr)
library(readr)
source(here("raw_data_analysis/code/shared_figure_formatting.R"))
```

```{r import_functions}
# Function to extract WT constructs or to find which construct the strain is from experiment name
construct_extraction <- function(strain_name){
  construct_name <- str_extract(strain_name,"mod[A-Z0]")
  construct_name[is.na(construct_name)] <- str_extract(strain_name[is.na(construct_name)],"WT")
  construct_name
}

# Function to extract experimental replicate from experiment name
replicate_extraction <- function(experiment_name){
  experimental_replicate <- str_extract(experiment_name,"(?<=_n)[12](?=/)")
  experimental_replicate
}

# function to calculate standard error
standard_error <- function(x) sd(x) / sqrt(length(x))

# Calculate fluorescence relative to mod0 or WT
norm_fluo_cal <- function(fluo_tibble, norm_to = "mod0"){
  fluo_tibble %>%
    mutate(base_fluor = filter(., construct == norm_to) %>%
             pull(c_mCherry_100_per_OD_at_max_local_gr) %>%
             mean()) %>%
    group_by(construct) %>%
  mutate( relative_abundance_protein = c_mCherry_100_per_OD_at_max_local_gr / base_fluor)
}

# Calculate RNA relative to mod0 or WT
norm_RNA_cal <- function(RNA_tibble, norm_to = "mod0"){
  RNA_tibble %>%
    mutate(base_RNA = filter(., construct == norm_to) %>%
             pull(delta_cq) %>%
             mean()) %>%
    group_by(construct) %>%
  mutate( relative_abundance_RNA = delta_cq - base_RNA)
}

```

```{r import_data_protein}
## Protein data sets need to be imported separately due to differing naming conventions

RPS3_protein <- read.csv(here("raw_data_analysis/data/norm_platereader/motif_context_dependence/pRPS3-mCh-tRPS3/pRPS3-mCh-tRPS3_both_reps.csv")) %>%
  filter(strain != c("null")) %>%
  separate(strain,into = c("strain","bio_rep"), sep = "_clone_") %>%
  mutate(promoter = "pRPS3") 

TSA1_protein <- read.csv(here("raw_data_analysis/data/norm_platereader/motif_context_dependence/pTSA1-mCh-tTSA1/pTSA1-mCh-tTSA1_both_reps.csv")) %>%
  filter(strain != "null") %>%
  separate(strain,into = c("strain","bio_rep"),sep = " clone ") %>%
  mutate(promoter = "pTSA1")

PIR1_protein <- read.csv(here("raw_data_analysis/data/norm_platereader/motif_context_dependence/pPIR1-mCh-tPIR1/pPIR1-mCh-tPIR1_both_reps.csv")) %>%
  filter(strain != "null") %>%
  separate(strain,into = c("strain","bio_rep"),sep = " clone ") %>%
  mutate(promoter = "pPIR1")
```

```{r norm_protein}

RPS3_protein_norm <- RPS3_protein %>%
  filter(strain != "POT1-ccdB") %>% 
  mutate(construct =construct_extraction(strain),
         exp_rep = replicate_extraction(experiment)) %>%
  group_by(exp_rep) %>%
  group_modify(~norm_fluo_cal(.x))


TSA1_protein_norm <- TSA1_protein %>%
  filter(strain != "POT1-ccdB") %>% 
  mutate(construct =construct_extraction(strain),
         exp_rep = replicate_extraction(experiment)) %>%
  group_by(exp_rep) %>%
  group_modify(~norm_fluo_cal(.x))

RPS3_TSA1_protein <- RPS3_protein_norm %>%
  bind_rows(TSA1_protein_norm) %>%
  inner_join(construct_to_label_dictionary_TSA1_RPS3) %>%
  select(-experiment, -X, -strain, - c_mCherry_100_per_OD_at_max_local_gr, - base_fluor, -construct) %>% 
  ungroup()

 PIR1_protein_norm <- PIR1_protein %>%
  filter(strain != "POT1-ccdB") %>% 
  mutate(construct =construct_extraction(strain),
         exp_rep = replicate_extraction(experiment)) %>%
  group_by(exp_rep) %>%
  group_modify(~norm_fluo_cal(.x, "WT")) %>%
  inner_join(construct_to_label_dictionary_PIR1) %>%
  ungroup() %>%
  select(-experiment, -X, -strain, - c_mCherry_100_per_OD_at_max_local_gr, - base_fluor, -construct)
```

```{r import_data_rna}
RPS3_RNA <- 
  read_csv(here("./raw_data_analysis/data/norm_qpcr/motif_context_dependence/pRPS3_pPGK1_pSRO9_tRPS3_deltadeltacq_platesnorm_summarise.csv")) %>%
  filter(promoter == "pRPS3")

TSA1_RNA <- read_csv(here("./raw_data_analysis/data/norm_qpcr/motif_context_dependence/pTSA1_pPGK1_pSRO9_tTSA1_deltadeltacq_platesnorm_summarise.csv")) %>%
  filter(promoter == "pTSA1")

RPS3_TSA1_RNA <- 
  bind_rows(RPS3_RNA, TSA1_RNA) %>%
  inner_join(construct_to_label_dictionary_TSA1_RPS3) %>%
  transmute(promoter, 
            bio_rep = str_extract(bio_rep, "[123456]"), 
            label, 
            relative_abundance_mrna = rel_abund_delta_deltacq)

PIR1_RNA <- read_csv(here("./raw_data_analysis/data/norm_qpcr/motif_context_dependence/pPIR1_pPGK1_pSRO9_tPIR1_deltadeltacq_platesnorm_summarise.csv")) %>%
  filter(promoter == "pPIR1") %>%
  inner_join(construct_to_label_dictionary_PIR1) %>%
  transmute(promoter, 
            bio_rep = str_extract(bio_rep, "[123456]"), 
            label, 
            relative_abundance_mrna = rel_abund_delta_deltacq)
```

```{r join_protein_rna_data,echo = TRUE, results = "show"}
RPS3_TSA1_protein_and_RNA_data <- RPS3_TSA1_protein %>%
  inner_join(RPS3_TSA1_RNA) %>%
  mutate(promoter = factor(str_remove(promoter, "p"), levels = c("RPS3", "TSA1")),
         label = factor(label, levels = rev(c("WT", "mod_NGG", "mod_HTH", "mod_HNH", "mod_NTN", "mod_NAA", "mod_NNN"))))
RPS3_TSA1_protein_and_RNA_data

PIR1_protein_and_RNA_data <- PIR1_protein_norm  %>%
  inner_join(PIR1_RNA) %>%
  mutate(promoter = factor(str_remove(promoter, "p"), levels = c("PIR1")),
         label = factor(label, levels = c("WT", "mod_NTHHH", "mod_ANHHH", "mod_ATNHH", "mod_ATHNH", "mod_ATNNN", "mod_ANNNN", "mod_NTNNN")))
PIR1_protein_and_RNA_data
```

```{r mean_protein_rna_over_bio_reps}
mean_RPS3_TSA1_protein_and_RNA_data <- RPS3_TSA1_protein_and_RNA_data %>%
  group_by(promoter, label) %>%
  summarise(mean_relative_abundance_protein = mean(relative_abundance_protein),
            se_relative_abundance_protein = standard_error(relative_abundance_protein),
            mean_relative_abundance_mrna = mean(relative_abundance_mrna),
            se_relative_abundance_mrna = standard_error(relative_abundance_mrna),
            .groups = "drop")

mean_PIR1_protein_and_RNA_data <- PIR1_protein_and_RNA_data %>%
  group_by(promoter, label) %>%
  summarise(mean_relative_abundance_protein = mean(relative_abundance_protein),
            se_relative_abundance_protein = standard_error(relative_abundance_protein),
            mean_relative_abundance_mrna = mean(relative_abundance_mrna),
            se_relative_abundance_mrna = standard_error(relative_abundance_mrna),
            .groups = "drop")
```

```{r calc_mean_protein_rna_correlation}
r_cor_data_RPS3_TSA1 <- 
  mean_RPS3_TSA1_protein_and_RNA_data %>% 
  group_by(promoter) %>% 
  summarise(cor = round(cor(mean_relative_abundance_mrna,
                            mean_relative_abundance_protein),
                        2)) %>%
  mutate(cor_label = str_c("R = ", cor))

r_cor_data_PIR1 <- 
  mean_PIR1_protein_and_RNA_data %>% 
  group_by(promoter) %>% 
  summarise(cor = round(cor(mean_relative_abundance_mrna,
                            mean_relative_abundance_protein),
                        2)) %>%
  mutate(cor_label = str_c("R = ", cor))
```


```{r plot_protein_vs_rna_RPS3_TSA1, fig.width = 4.5, fig.height = 6}

RPS3_TSA1_protein_and_RNA_plot <- 
  ggplot(mean_RPS3_TSA1_protein_and_RNA_data) +
  protein_vs_RNA_figure_options +
  labs(y="Relative Protein Abundance", 
       x = "Relative mRNA Abundance", 
       colour = "Construct") +
  coord_equal(xlim = c(0.2, 2.0), 
              ylim= c(0.2, 2.0), 
              expand = FALSE) +
  geom_text(aes(label = cor_label), 
            data = r_cor_data_RPS3_TSA1, 
            y = 0.25, 
            x= -0.6, 
            size = 3, 
            hjust = 0, 
            vjust = 1) +
 scale_color_manual(values = rev(RPS3_TSA1_colour_scheme))

RPS3_TSA1_protein_and_RNA_plot
```

```{r plot_protein_vs_rna_PIR1, fig.width = 4.5, fig.height = 6}
PIR1_protein_and_RNA_plot <- 
  ggplot(mean_PIR1_protein_and_RNA_data) + 
  protein_vs_RNA_figure_options +
  labs(y="Relative Protein Abundance", 
       x = "Relative mRNA\n Abundance", 
       colour = "Construct")  +
  coord_equal(xlim = c(0.4, 4.0), 
              ylim = c(0.4, 4.0), 
              expand = FALSE) + 
  geom_text(aes(label = cor_label), 
            data = r_cor_data_PIR1, 
            y = 0.4, 
            x= -0.3, 
            size = 3, 
            hjust = 0, 
            vjust = 1) +
 scale_color_manual(values = rev(PIR1_colour_scheme))

PIR1_protein_and_RNA_plot
```

```{r plot_both}
RPS3_TSA1_PIR1_protein_and_RNA_plot <- 
  plot_grid(RPS3_TSA1_protein_and_RNA_plot, 
            PIR1_protein_and_RNA_plot, 
            align = "vh", 
            axis = "lb")

RPS3_TSA1_PIR1_protein_and_RNA_plot

ggsave(here("supplementary_data_chapter/figures/RPS3_TSA1_PIR1_protein_and_RNA_plot.png"),RPS3_TSA1_PIR1_protein_and_RNA_plot,
       width = 160, 
       height = 100,
       units = "mm",
       dpi = 300)

```
